
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AvailabilityBlock` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AvailabilityBlock
 * 
 */
export type AvailabilityBlockModel = runtime.Types.Result.DefaultSelection<Prisma.$AvailabilityBlockPayload>

export type AggregateAvailabilityBlock = {
  _count: AvailabilityBlockCountAggregateOutputType | null
  _min: AvailabilityBlockMinAggregateOutputType | null
  _max: AvailabilityBlockMaxAggregateOutputType | null
}

export type AvailabilityBlockMinAggregateOutputType = {
  id: string | null
  mentorId: string | null
  startAt: Date | null
  endAt: Date | null
  seriesId: string | null
  repeatUntil: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AvailabilityBlockMaxAggregateOutputType = {
  id: string | null
  mentorId: string | null
  startAt: Date | null
  endAt: Date | null
  seriesId: string | null
  repeatUntil: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AvailabilityBlockCountAggregateOutputType = {
  id: number
  mentorId: number
  startAt: number
  endAt: number
  seriesId: number
  repeatUntil: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AvailabilityBlockMinAggregateInputType = {
  id?: true
  mentorId?: true
  startAt?: true
  endAt?: true
  seriesId?: true
  repeatUntil?: true
  createdAt?: true
  updatedAt?: true
}

export type AvailabilityBlockMaxAggregateInputType = {
  id?: true
  mentorId?: true
  startAt?: true
  endAt?: true
  seriesId?: true
  repeatUntil?: true
  createdAt?: true
  updatedAt?: true
}

export type AvailabilityBlockCountAggregateInputType = {
  id?: true
  mentorId?: true
  startAt?: true
  endAt?: true
  seriesId?: true
  repeatUntil?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AvailabilityBlockAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvailabilityBlock to aggregate.
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailabilityBlocks to fetch.
   */
  orderBy?: Prisma.AvailabilityBlockOrderByWithRelationInput | Prisma.AvailabilityBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AvailabilityBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailabilityBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailabilityBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AvailabilityBlocks
  **/
  _count?: true | AvailabilityBlockCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AvailabilityBlockMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AvailabilityBlockMaxAggregateInputType
}

export type GetAvailabilityBlockAggregateType<T extends AvailabilityBlockAggregateArgs> = {
      [P in keyof T & keyof AggregateAvailabilityBlock]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAvailabilityBlock[P]>
    : Prisma.GetScalarType<T[P], AggregateAvailabilityBlock[P]>
}




export type AvailabilityBlockGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AvailabilityBlockWhereInput
  orderBy?: Prisma.AvailabilityBlockOrderByWithAggregationInput | Prisma.AvailabilityBlockOrderByWithAggregationInput[]
  by: Prisma.AvailabilityBlockScalarFieldEnum[] | Prisma.AvailabilityBlockScalarFieldEnum
  having?: Prisma.AvailabilityBlockScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AvailabilityBlockCountAggregateInputType | true
  _min?: AvailabilityBlockMinAggregateInputType
  _max?: AvailabilityBlockMaxAggregateInputType
}

export type AvailabilityBlockGroupByOutputType = {
  id: string
  mentorId: string
  startAt: Date
  endAt: Date
  seriesId: string | null
  repeatUntil: Date | null
  createdAt: Date
  updatedAt: Date
  _count: AvailabilityBlockCountAggregateOutputType | null
  _min: AvailabilityBlockMinAggregateOutputType | null
  _max: AvailabilityBlockMaxAggregateOutputType | null
}

export type GetAvailabilityBlockGroupByPayload<T extends AvailabilityBlockGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AvailabilityBlockGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AvailabilityBlockGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AvailabilityBlockGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AvailabilityBlockGroupByOutputType[P]>
      }
    >
  >



export type AvailabilityBlockWhereInput = {
  AND?: Prisma.AvailabilityBlockWhereInput | Prisma.AvailabilityBlockWhereInput[]
  OR?: Prisma.AvailabilityBlockWhereInput[]
  NOT?: Prisma.AvailabilityBlockWhereInput | Prisma.AvailabilityBlockWhereInput[]
  id?: Prisma.UuidFilter<"AvailabilityBlock"> | string
  mentorId?: Prisma.UuidFilter<"AvailabilityBlock"> | string
  startAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  endAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  seriesId?: Prisma.UuidNullableFilter<"AvailabilityBlock"> | string | null
  repeatUntil?: Prisma.DateTimeNullableFilter<"AvailabilityBlock"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  mentor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
  proposals?: Prisma.TimeProposalListRelationFilter
}

export type AvailabilityBlockOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  seriesId?: Prisma.SortOrderInput | Prisma.SortOrder
  repeatUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mentor?: Prisma.UserOrderByWithRelationInput
  appointments?: Prisma.AppointmentOrderByRelationAggregateInput
  proposals?: Prisma.TimeProposalOrderByRelationAggregateInput
}

export type AvailabilityBlockWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AvailabilityBlockWhereInput | Prisma.AvailabilityBlockWhereInput[]
  OR?: Prisma.AvailabilityBlockWhereInput[]
  NOT?: Prisma.AvailabilityBlockWhereInput | Prisma.AvailabilityBlockWhereInput[]
  mentorId?: Prisma.UuidFilter<"AvailabilityBlock"> | string
  startAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  endAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  seriesId?: Prisma.UuidNullableFilter<"AvailabilityBlock"> | string | null
  repeatUntil?: Prisma.DateTimeNullableFilter<"AvailabilityBlock"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  mentor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  appointments?: Prisma.AppointmentListRelationFilter
  proposals?: Prisma.TimeProposalListRelationFilter
}, "id">

export type AvailabilityBlockOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  seriesId?: Prisma.SortOrderInput | Prisma.SortOrder
  repeatUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AvailabilityBlockCountOrderByAggregateInput
  _max?: Prisma.AvailabilityBlockMaxOrderByAggregateInput
  _min?: Prisma.AvailabilityBlockMinOrderByAggregateInput
}

export type AvailabilityBlockScalarWhereWithAggregatesInput = {
  AND?: Prisma.AvailabilityBlockScalarWhereWithAggregatesInput | Prisma.AvailabilityBlockScalarWhereWithAggregatesInput[]
  OR?: Prisma.AvailabilityBlockScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AvailabilityBlockScalarWhereWithAggregatesInput | Prisma.AvailabilityBlockScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AvailabilityBlock"> | string
  mentorId?: Prisma.UuidWithAggregatesFilter<"AvailabilityBlock"> | string
  startAt?: Prisma.DateTimeWithAggregatesFilter<"AvailabilityBlock"> | Date | string
  endAt?: Prisma.DateTimeWithAggregatesFilter<"AvailabilityBlock"> | Date | string
  seriesId?: Prisma.UuidNullableWithAggregatesFilter<"AvailabilityBlock"> | string | null
  repeatUntil?: Prisma.DateTimeNullableWithAggregatesFilter<"AvailabilityBlock"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AvailabilityBlock"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AvailabilityBlock"> | Date | string
}

export type AvailabilityBlockCreateInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  mentor: Prisma.UserCreateNestedOneWithoutAvailabilityBlocksInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutBlockInput
  proposals?: Prisma.TimeProposalCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockUncheckedCreateInput = {
  id?: string
  mentorId: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutBlockInput
  proposals?: Prisma.TimeProposalUncheckedCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentor?: Prisma.UserUpdateOneRequiredWithoutAvailabilityBlocksNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutBlockNestedInput
  proposals?: Prisma.TimeProposalUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutBlockNestedInput
  proposals?: Prisma.TimeProposalUncheckedUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockCreateManyInput = {
  id?: string
  mentorId: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailabilityBlockUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailabilityBlockUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AvailabilityBlockListRelationFilter = {
  every?: Prisma.AvailabilityBlockWhereInput
  some?: Prisma.AvailabilityBlockWhereInput
  none?: Prisma.AvailabilityBlockWhereInput
}

export type AvailabilityBlockOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AvailabilityBlockCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  seriesId?: Prisma.SortOrder
  repeatUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailabilityBlockMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  seriesId?: Prisma.SortOrder
  repeatUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailabilityBlockMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  seriesId?: Prisma.SortOrder
  repeatUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AvailabilityBlockNullableScalarRelationFilter = {
  is?: Prisma.AvailabilityBlockWhereInput | null
  isNot?: Prisma.AvailabilityBlockWhereInput | null
}

export type AvailabilityBlockScalarRelationFilter = {
  is?: Prisma.AvailabilityBlockWhereInput
  isNot?: Prisma.AvailabilityBlockWhereInput
}

export type AvailabilityBlockCreateNestedManyWithoutMentorInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput> | Prisma.AvailabilityBlockCreateWithoutMentorInput[] | Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput | Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput[]
  createMany?: Prisma.AvailabilityBlockCreateManyMentorInputEnvelope
  connect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
}

export type AvailabilityBlockUncheckedCreateNestedManyWithoutMentorInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput> | Prisma.AvailabilityBlockCreateWithoutMentorInput[] | Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput | Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput[]
  createMany?: Prisma.AvailabilityBlockCreateManyMentorInputEnvelope
  connect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
}

export type AvailabilityBlockUpdateManyWithoutMentorNestedInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput> | Prisma.AvailabilityBlockCreateWithoutMentorInput[] | Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput | Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput[]
  upsert?: Prisma.AvailabilityBlockUpsertWithWhereUniqueWithoutMentorInput | Prisma.AvailabilityBlockUpsertWithWhereUniqueWithoutMentorInput[]
  createMany?: Prisma.AvailabilityBlockCreateManyMentorInputEnvelope
  set?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  disconnect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  delete?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  connect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  update?: Prisma.AvailabilityBlockUpdateWithWhereUniqueWithoutMentorInput | Prisma.AvailabilityBlockUpdateWithWhereUniqueWithoutMentorInput[]
  updateMany?: Prisma.AvailabilityBlockUpdateManyWithWhereWithoutMentorInput | Prisma.AvailabilityBlockUpdateManyWithWhereWithoutMentorInput[]
  deleteMany?: Prisma.AvailabilityBlockScalarWhereInput | Prisma.AvailabilityBlockScalarWhereInput[]
}

export type AvailabilityBlockUncheckedUpdateManyWithoutMentorNestedInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput> | Prisma.AvailabilityBlockCreateWithoutMentorInput[] | Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput | Prisma.AvailabilityBlockCreateOrConnectWithoutMentorInput[]
  upsert?: Prisma.AvailabilityBlockUpsertWithWhereUniqueWithoutMentorInput | Prisma.AvailabilityBlockUpsertWithWhereUniqueWithoutMentorInput[]
  createMany?: Prisma.AvailabilityBlockCreateManyMentorInputEnvelope
  set?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  disconnect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  delete?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  connect?: Prisma.AvailabilityBlockWhereUniqueInput | Prisma.AvailabilityBlockWhereUniqueInput[]
  update?: Prisma.AvailabilityBlockUpdateWithWhereUniqueWithoutMentorInput | Prisma.AvailabilityBlockUpdateWithWhereUniqueWithoutMentorInput[]
  updateMany?: Prisma.AvailabilityBlockUpdateManyWithWhereWithoutMentorInput | Prisma.AvailabilityBlockUpdateManyWithWhereWithoutMentorInput[]
  deleteMany?: Prisma.AvailabilityBlockScalarWhereInput | Prisma.AvailabilityBlockScalarWhereInput[]
}

export type AvailabilityBlockCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.AvailabilityBlockWhereUniqueInput
}

export type AvailabilityBlockUpdateOneWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.AvailabilityBlockUpsertWithoutAppointmentsInput
  disconnect?: Prisma.AvailabilityBlockWhereInput | boolean
  delete?: Prisma.AvailabilityBlockWhereInput | boolean
  connect?: Prisma.AvailabilityBlockWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AvailabilityBlockUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.AvailabilityBlockUpdateWithoutAppointmentsInput>, Prisma.AvailabilityBlockUncheckedUpdateWithoutAppointmentsInput>
}

export type AvailabilityBlockCreateNestedOneWithoutProposalsInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutProposalsInput>
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutProposalsInput
  connect?: Prisma.AvailabilityBlockWhereUniqueInput
}

export type AvailabilityBlockUpdateOneRequiredWithoutProposalsNestedInput = {
  create?: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutProposalsInput>
  connectOrCreate?: Prisma.AvailabilityBlockCreateOrConnectWithoutProposalsInput
  upsert?: Prisma.AvailabilityBlockUpsertWithoutProposalsInput
  connect?: Prisma.AvailabilityBlockWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AvailabilityBlockUpdateToOneWithWhereWithoutProposalsInput, Prisma.AvailabilityBlockUpdateWithoutProposalsInput>, Prisma.AvailabilityBlockUncheckedUpdateWithoutProposalsInput>
}

export type AvailabilityBlockCreateWithoutMentorInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentCreateNestedManyWithoutBlockInput
  proposals?: Prisma.TimeProposalCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockUncheckedCreateWithoutMentorInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutBlockInput
  proposals?: Prisma.TimeProposalUncheckedCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockCreateOrConnectWithoutMentorInput = {
  where: Prisma.AvailabilityBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput>
}

export type AvailabilityBlockCreateManyMentorInputEnvelope = {
  data: Prisma.AvailabilityBlockCreateManyMentorInput | Prisma.AvailabilityBlockCreateManyMentorInput[]
  skipDuplicates?: boolean
}

export type AvailabilityBlockUpsertWithWhereUniqueWithoutMentorInput = {
  where: Prisma.AvailabilityBlockWhereUniqueInput
  update: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutMentorInput>
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedCreateWithoutMentorInput>
}

export type AvailabilityBlockUpdateWithWhereUniqueWithoutMentorInput = {
  where: Prisma.AvailabilityBlockWhereUniqueInput
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutMentorInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutMentorInput>
}

export type AvailabilityBlockUpdateManyWithWhereWithoutMentorInput = {
  where: Prisma.AvailabilityBlockScalarWhereInput
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateManyMutationInput, Prisma.AvailabilityBlockUncheckedUpdateManyWithoutMentorInput>
}

export type AvailabilityBlockScalarWhereInput = {
  AND?: Prisma.AvailabilityBlockScalarWhereInput | Prisma.AvailabilityBlockScalarWhereInput[]
  OR?: Prisma.AvailabilityBlockScalarWhereInput[]
  NOT?: Prisma.AvailabilityBlockScalarWhereInput | Prisma.AvailabilityBlockScalarWhereInput[]
  id?: Prisma.UuidFilter<"AvailabilityBlock"> | string
  mentorId?: Prisma.UuidFilter<"AvailabilityBlock"> | string
  startAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  endAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  seriesId?: Prisma.UuidNullableFilter<"AvailabilityBlock"> | string | null
  repeatUntil?: Prisma.DateTimeNullableFilter<"AvailabilityBlock"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AvailabilityBlock"> | Date | string
}

export type AvailabilityBlockCreateWithoutAppointmentsInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  mentor: Prisma.UserCreateNestedOneWithoutAvailabilityBlocksInput
  proposals?: Prisma.TimeProposalCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockUncheckedCreateWithoutAppointmentsInput = {
  id?: string
  mentorId: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  proposals?: Prisma.TimeProposalUncheckedCreateNestedManyWithoutProposedBlockInput
}

export type AvailabilityBlockCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.AvailabilityBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutAppointmentsInput>
}

export type AvailabilityBlockUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.AvailabilityBlockWhereInput
}

export type AvailabilityBlockUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.AvailabilityBlockWhereInput
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutAppointmentsInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutAppointmentsInput>
}

export type AvailabilityBlockUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentor?: Prisma.UserUpdateOneRequiredWithoutAvailabilityBlocksNestedInput
  proposals?: Prisma.TimeProposalUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposals?: Prisma.TimeProposalUncheckedUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockCreateWithoutProposalsInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  mentor: Prisma.UserCreateNestedOneWithoutAvailabilityBlocksInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutBlockInput
}

export type AvailabilityBlockUncheckedCreateWithoutProposalsInput = {
  id?: string
  mentorId: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutBlockInput
}

export type AvailabilityBlockCreateOrConnectWithoutProposalsInput = {
  where: Prisma.AvailabilityBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutProposalsInput>
}

export type AvailabilityBlockUpsertWithoutProposalsInput = {
  update: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutProposalsInput>
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedCreateWithoutProposalsInput>
  where?: Prisma.AvailabilityBlockWhereInput
}

export type AvailabilityBlockUpdateToOneWithWhereWithoutProposalsInput = {
  where?: Prisma.AvailabilityBlockWhereInput
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateWithoutProposalsInput, Prisma.AvailabilityBlockUncheckedUpdateWithoutProposalsInput>
}

export type AvailabilityBlockUpdateWithoutProposalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentor?: Prisma.UserUpdateOneRequiredWithoutAvailabilityBlocksNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutBlockNestedInput
}

export type AvailabilityBlockUncheckedUpdateWithoutProposalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutBlockNestedInput
}

export type AvailabilityBlockCreateManyMentorInput = {
  id?: string
  startAt: Date | string
  endAt: Date | string
  seriesId?: string | null
  repeatUntil?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AvailabilityBlockUpdateWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUpdateManyWithoutBlockNestedInput
  proposals?: Prisma.TimeProposalUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockUncheckedUpdateWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutBlockNestedInput
  proposals?: Prisma.TimeProposalUncheckedUpdateManyWithoutProposedBlockNestedInput
}

export type AvailabilityBlockUncheckedUpdateManyWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seriesId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repeatUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AvailabilityBlockCountOutputType
 */

export type AvailabilityBlockCountOutputType = {
  appointments: number
  proposals: number
}

export type AvailabilityBlockCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | AvailabilityBlockCountOutputTypeCountAppointmentsArgs
  proposals?: boolean | AvailabilityBlockCountOutputTypeCountProposalsArgs
}

/**
 * AvailabilityBlockCountOutputType without action
 */
export type AvailabilityBlockCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlockCountOutputType
   */
  select?: Prisma.AvailabilityBlockCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AvailabilityBlockCountOutputType without action
 */
export type AvailabilityBlockCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
}

/**
 * AvailabilityBlockCountOutputType without action
 */
export type AvailabilityBlockCountOutputTypeCountProposalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeProposalWhereInput
}


export type AvailabilityBlockSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  startAt?: boolean
  endAt?: boolean
  seriesId?: boolean
  repeatUntil?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.AvailabilityBlock$appointmentsArgs<ExtArgs>
  proposals?: boolean | Prisma.AvailabilityBlock$proposalsArgs<ExtArgs>
  _count?: boolean | Prisma.AvailabilityBlockCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availabilityBlock"]>

export type AvailabilityBlockSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  startAt?: boolean
  endAt?: boolean
  seriesId?: boolean
  repeatUntil?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availabilityBlock"]>

export type AvailabilityBlockSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  startAt?: boolean
  endAt?: boolean
  seriesId?: boolean
  repeatUntil?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["availabilityBlock"]>

export type AvailabilityBlockSelectScalar = {
  id?: boolean
  mentorId?: boolean
  startAt?: boolean
  endAt?: boolean
  seriesId?: boolean
  repeatUntil?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AvailabilityBlockOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mentorId" | "startAt" | "endAt" | "seriesId" | "repeatUntil" | "createdAt" | "updatedAt", ExtArgs["result"]["availabilityBlock"]>
export type AvailabilityBlockInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  appointments?: boolean | Prisma.AvailabilityBlock$appointmentsArgs<ExtArgs>
  proposals?: boolean | Prisma.AvailabilityBlock$proposalsArgs<ExtArgs>
  _count?: boolean | Prisma.AvailabilityBlockCountOutputTypeDefaultArgs<ExtArgs>
}
export type AvailabilityBlockIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AvailabilityBlockIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AvailabilityBlockPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AvailabilityBlock"
  objects: {
    mentor: Prisma.$UserPayload<ExtArgs>
    appointments: Prisma.$AppointmentPayload<ExtArgs>[]
    proposals: Prisma.$TimeProposalPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mentorId: string
    startAt: Date
    endAt: Date
    seriesId: string | null
    repeatUntil: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["availabilityBlock"]>
  composites: {}
}

export type AvailabilityBlockGetPayload<S extends boolean | null | undefined | AvailabilityBlockDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload, S>

export type AvailabilityBlockCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AvailabilityBlockFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AvailabilityBlockCountAggregateInputType | true
  }

export interface AvailabilityBlockDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AvailabilityBlock'], meta: { name: 'AvailabilityBlock' } }
  /**
   * Find zero or one AvailabilityBlock that matches the filter.
   * @param {AvailabilityBlockFindUniqueArgs} args - Arguments to find a AvailabilityBlock
   * @example
   * // Get one AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AvailabilityBlockFindUniqueArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AvailabilityBlock that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AvailabilityBlockFindUniqueOrThrowArgs} args - Arguments to find a AvailabilityBlock
   * @example
   * // Get one AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AvailabilityBlockFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvailabilityBlock that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockFindFirstArgs} args - Arguments to find a AvailabilityBlock
   * @example
   * // Get one AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AvailabilityBlockFindFirstArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockFindFirstArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvailabilityBlock that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockFindFirstOrThrowArgs} args - Arguments to find a AvailabilityBlock
   * @example
   * // Get one AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AvailabilityBlockFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AvailabilityBlocks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AvailabilityBlocks
   * const availabilityBlocks = await prisma.availabilityBlock.findMany()
   * 
   * // Get first 10 AvailabilityBlocks
   * const availabilityBlocks = await prisma.availabilityBlock.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const availabilityBlockWithIdOnly = await prisma.availabilityBlock.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AvailabilityBlockFindManyArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AvailabilityBlock.
   * @param {AvailabilityBlockCreateArgs} args - Arguments to create a AvailabilityBlock.
   * @example
   * // Create one AvailabilityBlock
   * const AvailabilityBlock = await prisma.availabilityBlock.create({
   *   data: {
   *     // ... data to create a AvailabilityBlock
   *   }
   * })
   * 
   */
  create<T extends AvailabilityBlockCreateArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockCreateArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AvailabilityBlocks.
   * @param {AvailabilityBlockCreateManyArgs} args - Arguments to create many AvailabilityBlocks.
   * @example
   * // Create many AvailabilityBlocks
   * const availabilityBlock = await prisma.availabilityBlock.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AvailabilityBlockCreateManyArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AvailabilityBlocks and returns the data saved in the database.
   * @param {AvailabilityBlockCreateManyAndReturnArgs} args - Arguments to create many AvailabilityBlocks.
   * @example
   * // Create many AvailabilityBlocks
   * const availabilityBlock = await prisma.availabilityBlock.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AvailabilityBlocks and only return the `id`
   * const availabilityBlockWithIdOnly = await prisma.availabilityBlock.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AvailabilityBlockCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AvailabilityBlock.
   * @param {AvailabilityBlockDeleteArgs} args - Arguments to delete one AvailabilityBlock.
   * @example
   * // Delete one AvailabilityBlock
   * const AvailabilityBlock = await prisma.availabilityBlock.delete({
   *   where: {
   *     // ... filter to delete one AvailabilityBlock
   *   }
   * })
   * 
   */
  delete<T extends AvailabilityBlockDeleteArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockDeleteArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AvailabilityBlock.
   * @param {AvailabilityBlockUpdateArgs} args - Arguments to update one AvailabilityBlock.
   * @example
   * // Update one AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AvailabilityBlockUpdateArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockUpdateArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AvailabilityBlocks.
   * @param {AvailabilityBlockDeleteManyArgs} args - Arguments to filter AvailabilityBlocks to delete.
   * @example
   * // Delete a few AvailabilityBlocks
   * const { count } = await prisma.availabilityBlock.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AvailabilityBlockDeleteManyArgs>(args?: Prisma.SelectSubset<T, AvailabilityBlockDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvailabilityBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AvailabilityBlocks
   * const availabilityBlock = await prisma.availabilityBlock.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AvailabilityBlockUpdateManyArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvailabilityBlocks and returns the data updated in the database.
   * @param {AvailabilityBlockUpdateManyAndReturnArgs} args - Arguments to update many AvailabilityBlocks.
   * @example
   * // Update many AvailabilityBlocks
   * const availabilityBlock = await prisma.availabilityBlock.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AvailabilityBlocks and only return the `id`
   * const availabilityBlockWithIdOnly = await prisma.availabilityBlock.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AvailabilityBlockUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AvailabilityBlock.
   * @param {AvailabilityBlockUpsertArgs} args - Arguments to update or create a AvailabilityBlock.
   * @example
   * // Update or create a AvailabilityBlock
   * const availabilityBlock = await prisma.availabilityBlock.upsert({
   *   create: {
   *     // ... data to create a AvailabilityBlock
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AvailabilityBlock we want to update
   *   }
   * })
   */
  upsert<T extends AvailabilityBlockUpsertArgs>(args: Prisma.SelectSubset<T, AvailabilityBlockUpsertArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AvailabilityBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockCountArgs} args - Arguments to filter AvailabilityBlocks to count.
   * @example
   * // Count the number of AvailabilityBlocks
   * const count = await prisma.availabilityBlock.count({
   *   where: {
   *     // ... the filter for the AvailabilityBlocks we want to count
   *   }
   * })
  **/
  count<T extends AvailabilityBlockCountArgs>(
    args?: Prisma.Subset<T, AvailabilityBlockCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AvailabilityBlockCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AvailabilityBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AvailabilityBlockAggregateArgs>(args: Prisma.Subset<T, AvailabilityBlockAggregateArgs>): Prisma.PrismaPromise<GetAvailabilityBlockAggregateType<T>>

  /**
   * Group by AvailabilityBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvailabilityBlockGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AvailabilityBlockGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AvailabilityBlockGroupByArgs['orderBy'] }
      : { orderBy?: AvailabilityBlockGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AvailabilityBlockGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAvailabilityBlockGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AvailabilityBlock model
 */
readonly fields: AvailabilityBlockFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AvailabilityBlock.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AvailabilityBlockClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mentor<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  appointments<T extends Prisma.AvailabilityBlock$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AvailabilityBlock$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  proposals<T extends Prisma.AvailabilityBlock$proposalsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AvailabilityBlock$proposalsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AvailabilityBlock model
 */
export interface AvailabilityBlockFieldRefs {
  readonly id: Prisma.FieldRef<"AvailabilityBlock", 'String'>
  readonly mentorId: Prisma.FieldRef<"AvailabilityBlock", 'String'>
  readonly startAt: Prisma.FieldRef<"AvailabilityBlock", 'DateTime'>
  readonly endAt: Prisma.FieldRef<"AvailabilityBlock", 'DateTime'>
  readonly seriesId: Prisma.FieldRef<"AvailabilityBlock", 'String'>
  readonly repeatUntil: Prisma.FieldRef<"AvailabilityBlock", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AvailabilityBlock", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AvailabilityBlock", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AvailabilityBlock findUnique
 */
export type AvailabilityBlockFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter, which AvailabilityBlock to fetch.
   */
  where: Prisma.AvailabilityBlockWhereUniqueInput
}

/**
 * AvailabilityBlock findUniqueOrThrow
 */
export type AvailabilityBlockFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter, which AvailabilityBlock to fetch.
   */
  where: Prisma.AvailabilityBlockWhereUniqueInput
}

/**
 * AvailabilityBlock findFirst
 */
export type AvailabilityBlockFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter, which AvailabilityBlock to fetch.
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailabilityBlocks to fetch.
   */
  orderBy?: Prisma.AvailabilityBlockOrderByWithRelationInput | Prisma.AvailabilityBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvailabilityBlocks.
   */
  cursor?: Prisma.AvailabilityBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailabilityBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailabilityBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailabilityBlocks.
   */
  distinct?: Prisma.AvailabilityBlockScalarFieldEnum | Prisma.AvailabilityBlockScalarFieldEnum[]
}

/**
 * AvailabilityBlock findFirstOrThrow
 */
export type AvailabilityBlockFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter, which AvailabilityBlock to fetch.
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailabilityBlocks to fetch.
   */
  orderBy?: Prisma.AvailabilityBlockOrderByWithRelationInput | Prisma.AvailabilityBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvailabilityBlocks.
   */
  cursor?: Prisma.AvailabilityBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailabilityBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailabilityBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailabilityBlocks.
   */
  distinct?: Prisma.AvailabilityBlockScalarFieldEnum | Prisma.AvailabilityBlockScalarFieldEnum[]
}

/**
 * AvailabilityBlock findMany
 */
export type AvailabilityBlockFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter, which AvailabilityBlocks to fetch.
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvailabilityBlocks to fetch.
   */
  orderBy?: Prisma.AvailabilityBlockOrderByWithRelationInput | Prisma.AvailabilityBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AvailabilityBlocks.
   */
  cursor?: Prisma.AvailabilityBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvailabilityBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvailabilityBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvailabilityBlocks.
   */
  distinct?: Prisma.AvailabilityBlockScalarFieldEnum | Prisma.AvailabilityBlockScalarFieldEnum[]
}

/**
 * AvailabilityBlock create
 */
export type AvailabilityBlockCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * The data needed to create a AvailabilityBlock.
   */
  data: Prisma.XOR<Prisma.AvailabilityBlockCreateInput, Prisma.AvailabilityBlockUncheckedCreateInput>
}

/**
 * AvailabilityBlock createMany
 */
export type AvailabilityBlockCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AvailabilityBlocks.
   */
  data: Prisma.AvailabilityBlockCreateManyInput | Prisma.AvailabilityBlockCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AvailabilityBlock createManyAndReturn
 */
export type AvailabilityBlockCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * The data used to create many AvailabilityBlocks.
   */
  data: Prisma.AvailabilityBlockCreateManyInput | Prisma.AvailabilityBlockCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AvailabilityBlock update
 */
export type AvailabilityBlockUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * The data needed to update a AvailabilityBlock.
   */
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateInput, Prisma.AvailabilityBlockUncheckedUpdateInput>
  /**
   * Choose, which AvailabilityBlock to update.
   */
  where: Prisma.AvailabilityBlockWhereUniqueInput
}

/**
 * AvailabilityBlock updateMany
 */
export type AvailabilityBlockUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AvailabilityBlocks.
   */
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateManyMutationInput, Prisma.AvailabilityBlockUncheckedUpdateManyInput>
  /**
   * Filter which AvailabilityBlocks to update
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * Limit how many AvailabilityBlocks to update.
   */
  limit?: number
}

/**
 * AvailabilityBlock updateManyAndReturn
 */
export type AvailabilityBlockUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * The data used to update AvailabilityBlocks.
   */
  data: Prisma.XOR<Prisma.AvailabilityBlockUpdateManyMutationInput, Prisma.AvailabilityBlockUncheckedUpdateManyInput>
  /**
   * Filter which AvailabilityBlocks to update
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * Limit how many AvailabilityBlocks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AvailabilityBlock upsert
 */
export type AvailabilityBlockUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * The filter to search for the AvailabilityBlock to update in case it exists.
   */
  where: Prisma.AvailabilityBlockWhereUniqueInput
  /**
   * In case the AvailabilityBlock found by the `where` argument doesn't exist, create a new AvailabilityBlock with this data.
   */
  create: Prisma.XOR<Prisma.AvailabilityBlockCreateInput, Prisma.AvailabilityBlockUncheckedCreateInput>
  /**
   * In case the AvailabilityBlock was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AvailabilityBlockUpdateInput, Prisma.AvailabilityBlockUncheckedUpdateInput>
}

/**
 * AvailabilityBlock delete
 */
export type AvailabilityBlockDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
  /**
   * Filter which AvailabilityBlock to delete.
   */
  where: Prisma.AvailabilityBlockWhereUniqueInput
}

/**
 * AvailabilityBlock deleteMany
 */
export type AvailabilityBlockDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvailabilityBlocks to delete
   */
  where?: Prisma.AvailabilityBlockWhereInput
  /**
   * Limit how many AvailabilityBlocks to delete.
   */
  limit?: number
}

/**
 * AvailabilityBlock.appointments
 */
export type AvailabilityBlock$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * AvailabilityBlock.proposals
 */
export type AvailabilityBlock$proposalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  where?: Prisma.TimeProposalWhereInput
  orderBy?: Prisma.TimeProposalOrderByWithRelationInput | Prisma.TimeProposalOrderByWithRelationInput[]
  cursor?: Prisma.TimeProposalWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TimeProposalScalarFieldEnum | Prisma.TimeProposalScalarFieldEnum[]
}

/**
 * AvailabilityBlock without action
 */
export type AvailabilityBlockDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvailabilityBlock
   */
  select?: Prisma.AvailabilityBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvailabilityBlock
   */
  omit?: Prisma.AvailabilityBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvailabilityBlockInclude<ExtArgs> | null
}
