
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventModality` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventModality
 * 
 */
export type EventModalityModel = runtime.Types.Result.DefaultSelection<Prisma.$EventModalityPayload>

export type AggregateEventModality = {
  _count: EventModalityCountAggregateOutputType | null
  _min: EventModalityMinAggregateOutputType | null
  _max: EventModalityMaxAggregateOutputType | null
}

export type EventModalityMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventModalityMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventModalityCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventModalityMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type EventModalityMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type EventModalityCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventModalityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventModality to aggregate.
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventModalities to fetch.
   */
  orderBy?: Prisma.EventModalityOrderByWithRelationInput | Prisma.EventModalityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventModalityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventModalities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventModalities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventModalities
  **/
  _count?: true | EventModalityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventModalityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventModalityMaxAggregateInputType
}

export type GetEventModalityAggregateType<T extends EventModalityAggregateArgs> = {
      [P in keyof T & keyof AggregateEventModality]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventModality[P]>
    : Prisma.GetScalarType<T[P], AggregateEventModality[P]>
}




export type EventModalityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventModalityWhereInput
  orderBy?: Prisma.EventModalityOrderByWithAggregationInput | Prisma.EventModalityOrderByWithAggregationInput[]
  by: Prisma.EventModalityScalarFieldEnum[] | Prisma.EventModalityScalarFieldEnum
  having?: Prisma.EventModalityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventModalityCountAggregateInputType | true
  _min?: EventModalityMinAggregateInputType
  _max?: EventModalityMaxAggregateInputType
}

export type EventModalityGroupByOutputType = {
  id: string
  title: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: EventModalityCountAggregateOutputType | null
  _min: EventModalityMinAggregateOutputType | null
  _max: EventModalityMaxAggregateOutputType | null
}

export type GetEventModalityGroupByPayload<T extends EventModalityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventModalityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventModalityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventModalityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventModalityGroupByOutputType[P]>
      }
    >
  >



export type EventModalityWhereInput = {
  AND?: Prisma.EventModalityWhereInput | Prisma.EventModalityWhereInput[]
  OR?: Prisma.EventModalityWhereInput[]
  NOT?: Prisma.EventModalityWhereInput | Prisma.EventModalityWhereInput[]
  id?: Prisma.UuidFilter<"EventModality"> | string
  title?: Prisma.StringFilter<"EventModality"> | string
  description?: Prisma.StringNullableFilter<"EventModality"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventModality"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventModality"> | Date | string
  events?: Prisma.EventListRelationFilter
}

export type EventModalityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  events?: Prisma.EventOrderByRelationAggregateInput
}

export type EventModalityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.EventModalityWhereInput | Prisma.EventModalityWhereInput[]
  OR?: Prisma.EventModalityWhereInput[]
  NOT?: Prisma.EventModalityWhereInput | Prisma.EventModalityWhereInput[]
  description?: Prisma.StringNullableFilter<"EventModality"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventModality"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventModality"> | Date | string
  events?: Prisma.EventListRelationFilter
}, "id" | "title">

export type EventModalityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventModalityCountOrderByAggregateInput
  _max?: Prisma.EventModalityMaxOrderByAggregateInput
  _min?: Prisma.EventModalityMinOrderByAggregateInput
}

export type EventModalityScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventModalityScalarWhereWithAggregatesInput | Prisma.EventModalityScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventModalityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventModalityScalarWhereWithAggregatesInput | Prisma.EventModalityScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"EventModality"> | string
  title?: Prisma.StringWithAggregatesFilter<"EventModality"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"EventModality"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventModality"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventModality"> | Date | string
}

export type EventModalityCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  events?: Prisma.EventCreateNestedManyWithoutModalityInput
}

export type EventModalityUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  events?: Prisma.EventUncheckedCreateNestedManyWithoutModalityInput
}

export type EventModalityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.EventUpdateManyWithoutModalityNestedInput
}

export type EventModalityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.EventUncheckedUpdateManyWithoutModalityNestedInput
}

export type EventModalityCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventModalityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventModalityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventModalityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventModalityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventModalityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventModalityScalarRelationFilter = {
  is?: Prisma.EventModalityWhereInput
  isNot?: Prisma.EventModalityWhereInput
}

export type EventModalityCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.EventModalityCreateWithoutEventsInput, Prisma.EventModalityUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.EventModalityCreateOrConnectWithoutEventsInput
  connect?: Prisma.EventModalityWhereUniqueInput
}

export type EventModalityUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.EventModalityCreateWithoutEventsInput, Prisma.EventModalityUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.EventModalityCreateOrConnectWithoutEventsInput
  upsert?: Prisma.EventModalityUpsertWithoutEventsInput
  connect?: Prisma.EventModalityWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventModalityUpdateToOneWithWhereWithoutEventsInput, Prisma.EventModalityUpdateWithoutEventsInput>, Prisma.EventModalityUncheckedUpdateWithoutEventsInput>
}

export type EventModalityCreateWithoutEventsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventModalityUncheckedCreateWithoutEventsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventModalityCreateOrConnectWithoutEventsInput = {
  where: Prisma.EventModalityWhereUniqueInput
  create: Prisma.XOR<Prisma.EventModalityCreateWithoutEventsInput, Prisma.EventModalityUncheckedCreateWithoutEventsInput>
}

export type EventModalityUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.EventModalityUpdateWithoutEventsInput, Prisma.EventModalityUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.EventModalityCreateWithoutEventsInput, Prisma.EventModalityUncheckedCreateWithoutEventsInput>
  where?: Prisma.EventModalityWhereInput
}

export type EventModalityUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.EventModalityWhereInput
  data: Prisma.XOR<Prisma.EventModalityUpdateWithoutEventsInput, Prisma.EventModalityUncheckedUpdateWithoutEventsInput>
}

export type EventModalityUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventModalityUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EventModalityCountOutputType
 */

export type EventModalityCountOutputType = {
  events: number
}

export type EventModalityCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | EventModalityCountOutputTypeCountEventsArgs
}

/**
 * EventModalityCountOutputType without action
 */
export type EventModalityCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModalityCountOutputType
   */
  select?: Prisma.EventModalityCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventModalityCountOutputType without action
 */
export type EventModalityCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventWhereInput
}


export type EventModalitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  events?: boolean | Prisma.EventModality$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.EventModalityCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventModality"]>

export type EventModalitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["eventModality"]>

export type EventModalitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["eventModality"]>

export type EventModalitySelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventModalityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["eventModality"]>
export type EventModalityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.EventModality$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.EventModalityCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventModalityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type EventModalityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $EventModalityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventModality"
  objects: {
    events: Prisma.$EventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventModality"]>
  composites: {}
}

export type EventModalityGetPayload<S extends boolean | null | undefined | EventModalityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventModalityPayload, S>

export type EventModalityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventModalityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventModalityCountAggregateInputType | true
  }

export interface EventModalityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventModality'], meta: { name: 'EventModality' } }
  /**
   * Find zero or one EventModality that matches the filter.
   * @param {EventModalityFindUniqueArgs} args - Arguments to find a EventModality
   * @example
   * // Get one EventModality
   * const eventModality = await prisma.eventModality.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventModalityFindUniqueArgs>(args: Prisma.SelectSubset<T, EventModalityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventModality that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventModalityFindUniqueOrThrowArgs} args - Arguments to find a EventModality
   * @example
   * // Get one EventModality
   * const eventModality = await prisma.eventModality.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventModalityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventModalityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventModality that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityFindFirstArgs} args - Arguments to find a EventModality
   * @example
   * // Get one EventModality
   * const eventModality = await prisma.eventModality.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventModalityFindFirstArgs>(args?: Prisma.SelectSubset<T, EventModalityFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventModality that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityFindFirstOrThrowArgs} args - Arguments to find a EventModality
   * @example
   * // Get one EventModality
   * const eventModality = await prisma.eventModality.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventModalityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventModalityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventModalities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventModalities
   * const eventModalities = await prisma.eventModality.findMany()
   * 
   * // Get first 10 EventModalities
   * const eventModalities = await prisma.eventModality.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventModalityWithIdOnly = await prisma.eventModality.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventModalityFindManyArgs>(args?: Prisma.SelectSubset<T, EventModalityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventModality.
   * @param {EventModalityCreateArgs} args - Arguments to create a EventModality.
   * @example
   * // Create one EventModality
   * const EventModality = await prisma.eventModality.create({
   *   data: {
   *     // ... data to create a EventModality
   *   }
   * })
   * 
   */
  create<T extends EventModalityCreateArgs>(args: Prisma.SelectSubset<T, EventModalityCreateArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventModalities.
   * @param {EventModalityCreateManyArgs} args - Arguments to create many EventModalities.
   * @example
   * // Create many EventModalities
   * const eventModality = await prisma.eventModality.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventModalityCreateManyArgs>(args?: Prisma.SelectSubset<T, EventModalityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventModalities and returns the data saved in the database.
   * @param {EventModalityCreateManyAndReturnArgs} args - Arguments to create many EventModalities.
   * @example
   * // Create many EventModalities
   * const eventModality = await prisma.eventModality.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventModalities and only return the `id`
   * const eventModalityWithIdOnly = await prisma.eventModality.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventModalityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventModalityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventModality.
   * @param {EventModalityDeleteArgs} args - Arguments to delete one EventModality.
   * @example
   * // Delete one EventModality
   * const EventModality = await prisma.eventModality.delete({
   *   where: {
   *     // ... filter to delete one EventModality
   *   }
   * })
   * 
   */
  delete<T extends EventModalityDeleteArgs>(args: Prisma.SelectSubset<T, EventModalityDeleteArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventModality.
   * @param {EventModalityUpdateArgs} args - Arguments to update one EventModality.
   * @example
   * // Update one EventModality
   * const eventModality = await prisma.eventModality.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventModalityUpdateArgs>(args: Prisma.SelectSubset<T, EventModalityUpdateArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventModalities.
   * @param {EventModalityDeleteManyArgs} args - Arguments to filter EventModalities to delete.
   * @example
   * // Delete a few EventModalities
   * const { count } = await prisma.eventModality.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventModalityDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventModalityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventModalities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventModalities
   * const eventModality = await prisma.eventModality.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventModalityUpdateManyArgs>(args: Prisma.SelectSubset<T, EventModalityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventModalities and returns the data updated in the database.
   * @param {EventModalityUpdateManyAndReturnArgs} args - Arguments to update many EventModalities.
   * @example
   * // Update many EventModalities
   * const eventModality = await prisma.eventModality.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventModalities and only return the `id`
   * const eventModalityWithIdOnly = await prisma.eventModality.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventModalityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventModalityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventModality.
   * @param {EventModalityUpsertArgs} args - Arguments to update or create a EventModality.
   * @example
   * // Update or create a EventModality
   * const eventModality = await prisma.eventModality.upsert({
   *   create: {
   *     // ... data to create a EventModality
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventModality we want to update
   *   }
   * })
   */
  upsert<T extends EventModalityUpsertArgs>(args: Prisma.SelectSubset<T, EventModalityUpsertArgs<ExtArgs>>): Prisma.Prisma__EventModalityClient<runtime.Types.Result.GetResult<Prisma.$EventModalityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventModalities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityCountArgs} args - Arguments to filter EventModalities to count.
   * @example
   * // Count the number of EventModalities
   * const count = await prisma.eventModality.count({
   *   where: {
   *     // ... the filter for the EventModalities we want to count
   *   }
   * })
  **/
  count<T extends EventModalityCountArgs>(
    args?: Prisma.Subset<T, EventModalityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventModalityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventModality.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventModalityAggregateArgs>(args: Prisma.Subset<T, EventModalityAggregateArgs>): Prisma.PrismaPromise<GetEventModalityAggregateType<T>>

  /**
   * Group by EventModality.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventModalityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventModalityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventModalityGroupByArgs['orderBy'] }
      : { orderBy?: EventModalityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventModalityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventModalityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventModality model
 */
readonly fields: EventModalityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventModality.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventModalityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  events<T extends Prisma.EventModality$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventModality$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventModality model
 */
export interface EventModalityFieldRefs {
  readonly id: Prisma.FieldRef<"EventModality", 'String'>
  readonly title: Prisma.FieldRef<"EventModality", 'String'>
  readonly description: Prisma.FieldRef<"EventModality", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventModality", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventModality", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventModality findUnique
 */
export type EventModalityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter, which EventModality to fetch.
   */
  where: Prisma.EventModalityWhereUniqueInput
}

/**
 * EventModality findUniqueOrThrow
 */
export type EventModalityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter, which EventModality to fetch.
   */
  where: Prisma.EventModalityWhereUniqueInput
}

/**
 * EventModality findFirst
 */
export type EventModalityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter, which EventModality to fetch.
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventModalities to fetch.
   */
  orderBy?: Prisma.EventModalityOrderByWithRelationInput | Prisma.EventModalityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventModalities.
   */
  cursor?: Prisma.EventModalityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventModalities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventModalities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventModalities.
   */
  distinct?: Prisma.EventModalityScalarFieldEnum | Prisma.EventModalityScalarFieldEnum[]
}

/**
 * EventModality findFirstOrThrow
 */
export type EventModalityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter, which EventModality to fetch.
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventModalities to fetch.
   */
  orderBy?: Prisma.EventModalityOrderByWithRelationInput | Prisma.EventModalityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventModalities.
   */
  cursor?: Prisma.EventModalityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventModalities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventModalities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventModalities.
   */
  distinct?: Prisma.EventModalityScalarFieldEnum | Prisma.EventModalityScalarFieldEnum[]
}

/**
 * EventModality findMany
 */
export type EventModalityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter, which EventModalities to fetch.
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventModalities to fetch.
   */
  orderBy?: Prisma.EventModalityOrderByWithRelationInput | Prisma.EventModalityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventModalities.
   */
  cursor?: Prisma.EventModalityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventModalities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventModalities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventModalities.
   */
  distinct?: Prisma.EventModalityScalarFieldEnum | Prisma.EventModalityScalarFieldEnum[]
}

/**
 * EventModality create
 */
export type EventModalityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * The data needed to create a EventModality.
   */
  data: Prisma.XOR<Prisma.EventModalityCreateInput, Prisma.EventModalityUncheckedCreateInput>
}

/**
 * EventModality createMany
 */
export type EventModalityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventModalities.
   */
  data: Prisma.EventModalityCreateManyInput | Prisma.EventModalityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventModality createManyAndReturn
 */
export type EventModalityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * The data used to create many EventModalities.
   */
  data: Prisma.EventModalityCreateManyInput | Prisma.EventModalityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventModality update
 */
export type EventModalityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * The data needed to update a EventModality.
   */
  data: Prisma.XOR<Prisma.EventModalityUpdateInput, Prisma.EventModalityUncheckedUpdateInput>
  /**
   * Choose, which EventModality to update.
   */
  where: Prisma.EventModalityWhereUniqueInput
}

/**
 * EventModality updateMany
 */
export type EventModalityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventModalities.
   */
  data: Prisma.XOR<Prisma.EventModalityUpdateManyMutationInput, Prisma.EventModalityUncheckedUpdateManyInput>
  /**
   * Filter which EventModalities to update
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * Limit how many EventModalities to update.
   */
  limit?: number
}

/**
 * EventModality updateManyAndReturn
 */
export type EventModalityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * The data used to update EventModalities.
   */
  data: Prisma.XOR<Prisma.EventModalityUpdateManyMutationInput, Prisma.EventModalityUncheckedUpdateManyInput>
  /**
   * Filter which EventModalities to update
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * Limit how many EventModalities to update.
   */
  limit?: number
}

/**
 * EventModality upsert
 */
export type EventModalityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * The filter to search for the EventModality to update in case it exists.
   */
  where: Prisma.EventModalityWhereUniqueInput
  /**
   * In case the EventModality found by the `where` argument doesn't exist, create a new EventModality with this data.
   */
  create: Prisma.XOR<Prisma.EventModalityCreateInput, Prisma.EventModalityUncheckedCreateInput>
  /**
   * In case the EventModality was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventModalityUpdateInput, Prisma.EventModalityUncheckedUpdateInput>
}

/**
 * EventModality delete
 */
export type EventModalityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
  /**
   * Filter which EventModality to delete.
   */
  where: Prisma.EventModalityWhereUniqueInput
}

/**
 * EventModality deleteMany
 */
export type EventModalityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventModalities to delete
   */
  where?: Prisma.EventModalityWhereInput
  /**
   * Limit how many EventModalities to delete.
   */
  limit?: number
}

/**
 * EventModality.events
 */
export type EventModality$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Event
   */
  select?: Prisma.EventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Event
   */
  omit?: Prisma.EventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventInclude<ExtArgs> | null
  where?: Prisma.EventWhereInput
  orderBy?: Prisma.EventOrderByWithRelationInput | Prisma.EventOrderByWithRelationInput[]
  cursor?: Prisma.EventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventScalarFieldEnum | Prisma.EventScalarFieldEnum[]
}

/**
 * EventModality without action
 */
export type EventModalityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventModality
   */
  select?: Prisma.EventModalitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventModality
   */
  omit?: Prisma.EventModalityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventModalityInclude<ExtArgs> | null
}
