
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventOrigin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventOrigin
 * 
 */
export type EventOriginModel = runtime.Types.Result.DefaultSelection<Prisma.$EventOriginPayload>

export type AggregateEventOrigin = {
  _count: EventOriginCountAggregateOutputType | null
  _min: EventOriginMinAggregateOutputType | null
  _max: EventOriginMaxAggregateOutputType | null
}

export type EventOriginMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventOriginMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventOriginCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventOriginMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type EventOriginMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type EventOriginCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventOriginAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventOrigin to aggregate.
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventOrigins to fetch.
   */
  orderBy?: Prisma.EventOriginOrderByWithRelationInput | Prisma.EventOriginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventOriginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventOrigins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventOrigins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventOrigins
  **/
  _count?: true | EventOriginCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventOriginMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventOriginMaxAggregateInputType
}

export type GetEventOriginAggregateType<T extends EventOriginAggregateArgs> = {
      [P in keyof T & keyof AggregateEventOrigin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventOrigin[P]>
    : Prisma.GetScalarType<T[P], AggregateEventOrigin[P]>
}




export type EventOriginGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventOriginWhereInput
  orderBy?: Prisma.EventOriginOrderByWithAggregationInput | Prisma.EventOriginOrderByWithAggregationInput[]
  by: Prisma.EventOriginScalarFieldEnum[] | Prisma.EventOriginScalarFieldEnum
  having?: Prisma.EventOriginScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventOriginCountAggregateInputType | true
  _min?: EventOriginMinAggregateInputType
  _max?: EventOriginMaxAggregateInputType
}

export type EventOriginGroupByOutputType = {
  id: string
  title: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: EventOriginCountAggregateOutputType | null
  _min: EventOriginMinAggregateOutputType | null
  _max: EventOriginMaxAggregateOutputType | null
}

export type GetEventOriginGroupByPayload<T extends EventOriginGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventOriginGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventOriginGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventOriginGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventOriginGroupByOutputType[P]>
      }
    >
  >



export type EventOriginWhereInput = {
  AND?: Prisma.EventOriginWhereInput | Prisma.EventOriginWhereInput[]
  OR?: Prisma.EventOriginWhereInput[]
  NOT?: Prisma.EventOriginWhereInput | Prisma.EventOriginWhereInput[]
  id?: Prisma.UuidFilter<"EventOrigin"> | string
  title?: Prisma.StringFilter<"EventOrigin"> | string
  description?: Prisma.StringNullableFilter<"EventOrigin"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventOrigin"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventOrigin"> | Date | string
  events?: Prisma.EventListRelationFilter
}

export type EventOriginOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  events?: Prisma.EventOrderByRelationAggregateInput
}

export type EventOriginWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.EventOriginWhereInput | Prisma.EventOriginWhereInput[]
  OR?: Prisma.EventOriginWhereInput[]
  NOT?: Prisma.EventOriginWhereInput | Prisma.EventOriginWhereInput[]
  description?: Prisma.StringNullableFilter<"EventOrigin"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventOrigin"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventOrigin"> | Date | string
  events?: Prisma.EventListRelationFilter
}, "id" | "title">

export type EventOriginOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventOriginCountOrderByAggregateInput
  _max?: Prisma.EventOriginMaxOrderByAggregateInput
  _min?: Prisma.EventOriginMinOrderByAggregateInput
}

export type EventOriginScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventOriginScalarWhereWithAggregatesInput | Prisma.EventOriginScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventOriginScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventOriginScalarWhereWithAggregatesInput | Prisma.EventOriginScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"EventOrigin"> | string
  title?: Prisma.StringWithAggregatesFilter<"EventOrigin"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"EventOrigin"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventOrigin"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventOrigin"> | Date | string
}

export type EventOriginCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  events?: Prisma.EventCreateNestedManyWithoutOriginInput
}

export type EventOriginUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  events?: Prisma.EventUncheckedCreateNestedManyWithoutOriginInput
}

export type EventOriginUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.EventUpdateManyWithoutOriginNestedInput
}

export type EventOriginUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.EventUncheckedUpdateManyWithoutOriginNestedInput
}

export type EventOriginCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventOriginUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventOriginUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventOriginCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventOriginMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventOriginMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventOriginScalarRelationFilter = {
  is?: Prisma.EventOriginWhereInput
  isNot?: Prisma.EventOriginWhereInput
}

export type EventOriginCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.EventOriginCreateWithoutEventsInput, Prisma.EventOriginUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.EventOriginCreateOrConnectWithoutEventsInput
  connect?: Prisma.EventOriginWhereUniqueInput
}

export type EventOriginUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.EventOriginCreateWithoutEventsInput, Prisma.EventOriginUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.EventOriginCreateOrConnectWithoutEventsInput
  upsert?: Prisma.EventOriginUpsertWithoutEventsInput
  connect?: Prisma.EventOriginWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventOriginUpdateToOneWithWhereWithoutEventsInput, Prisma.EventOriginUpdateWithoutEventsInput>, Prisma.EventOriginUncheckedUpdateWithoutEventsInput>
}

export type EventOriginCreateWithoutEventsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventOriginUncheckedCreateWithoutEventsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventOriginCreateOrConnectWithoutEventsInput = {
  where: Prisma.EventOriginWhereUniqueInput
  create: Prisma.XOR<Prisma.EventOriginCreateWithoutEventsInput, Prisma.EventOriginUncheckedCreateWithoutEventsInput>
}

export type EventOriginUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.EventOriginUpdateWithoutEventsInput, Prisma.EventOriginUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.EventOriginCreateWithoutEventsInput, Prisma.EventOriginUncheckedCreateWithoutEventsInput>
  where?: Prisma.EventOriginWhereInput
}

export type EventOriginUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.EventOriginWhereInput
  data: Prisma.XOR<Prisma.EventOriginUpdateWithoutEventsInput, Prisma.EventOriginUncheckedUpdateWithoutEventsInput>
}

export type EventOriginUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventOriginUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EventOriginCountOutputType
 */

export type EventOriginCountOutputType = {
  events: number
}

export type EventOriginCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | EventOriginCountOutputTypeCountEventsArgs
}

/**
 * EventOriginCountOutputType without action
 */
export type EventOriginCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOriginCountOutputType
   */
  select?: Prisma.EventOriginCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventOriginCountOutputType without action
 */
export type EventOriginCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventWhereInput
}


export type EventOriginSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  events?: boolean | Prisma.EventOrigin$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.EventOriginCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventOrigin"]>

export type EventOriginSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["eventOrigin"]>

export type EventOriginSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["eventOrigin"]>

export type EventOriginSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventOriginOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["eventOrigin"]>
export type EventOriginInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.EventOrigin$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.EventOriginCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventOriginIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type EventOriginIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $EventOriginPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventOrigin"
  objects: {
    events: Prisma.$EventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventOrigin"]>
  composites: {}
}

export type EventOriginGetPayload<S extends boolean | null | undefined | EventOriginDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventOriginPayload, S>

export type EventOriginCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventOriginFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventOriginCountAggregateInputType | true
  }

export interface EventOriginDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventOrigin'], meta: { name: 'EventOrigin' } }
  /**
   * Find zero or one EventOrigin that matches the filter.
   * @param {EventOriginFindUniqueArgs} args - Arguments to find a EventOrigin
   * @example
   * // Get one EventOrigin
   * const eventOrigin = await prisma.eventOrigin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventOriginFindUniqueArgs>(args: Prisma.SelectSubset<T, EventOriginFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventOrigin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventOriginFindUniqueOrThrowArgs} args - Arguments to find a EventOrigin
   * @example
   * // Get one EventOrigin
   * const eventOrigin = await prisma.eventOrigin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventOriginFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventOriginFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventOrigin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginFindFirstArgs} args - Arguments to find a EventOrigin
   * @example
   * // Get one EventOrigin
   * const eventOrigin = await prisma.eventOrigin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventOriginFindFirstArgs>(args?: Prisma.SelectSubset<T, EventOriginFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventOrigin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginFindFirstOrThrowArgs} args - Arguments to find a EventOrigin
   * @example
   * // Get one EventOrigin
   * const eventOrigin = await prisma.eventOrigin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventOriginFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventOriginFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventOrigins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventOrigins
   * const eventOrigins = await prisma.eventOrigin.findMany()
   * 
   * // Get first 10 EventOrigins
   * const eventOrigins = await prisma.eventOrigin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventOriginWithIdOnly = await prisma.eventOrigin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventOriginFindManyArgs>(args?: Prisma.SelectSubset<T, EventOriginFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventOrigin.
   * @param {EventOriginCreateArgs} args - Arguments to create a EventOrigin.
   * @example
   * // Create one EventOrigin
   * const EventOrigin = await prisma.eventOrigin.create({
   *   data: {
   *     // ... data to create a EventOrigin
   *   }
   * })
   * 
   */
  create<T extends EventOriginCreateArgs>(args: Prisma.SelectSubset<T, EventOriginCreateArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventOrigins.
   * @param {EventOriginCreateManyArgs} args - Arguments to create many EventOrigins.
   * @example
   * // Create many EventOrigins
   * const eventOrigin = await prisma.eventOrigin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventOriginCreateManyArgs>(args?: Prisma.SelectSubset<T, EventOriginCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventOrigins and returns the data saved in the database.
   * @param {EventOriginCreateManyAndReturnArgs} args - Arguments to create many EventOrigins.
   * @example
   * // Create many EventOrigins
   * const eventOrigin = await prisma.eventOrigin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventOrigins and only return the `id`
   * const eventOriginWithIdOnly = await prisma.eventOrigin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventOriginCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventOriginCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventOrigin.
   * @param {EventOriginDeleteArgs} args - Arguments to delete one EventOrigin.
   * @example
   * // Delete one EventOrigin
   * const EventOrigin = await prisma.eventOrigin.delete({
   *   where: {
   *     // ... filter to delete one EventOrigin
   *   }
   * })
   * 
   */
  delete<T extends EventOriginDeleteArgs>(args: Prisma.SelectSubset<T, EventOriginDeleteArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventOrigin.
   * @param {EventOriginUpdateArgs} args - Arguments to update one EventOrigin.
   * @example
   * // Update one EventOrigin
   * const eventOrigin = await prisma.eventOrigin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventOriginUpdateArgs>(args: Prisma.SelectSubset<T, EventOriginUpdateArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventOrigins.
   * @param {EventOriginDeleteManyArgs} args - Arguments to filter EventOrigins to delete.
   * @example
   * // Delete a few EventOrigins
   * const { count } = await prisma.eventOrigin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventOriginDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventOriginDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventOrigins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventOrigins
   * const eventOrigin = await prisma.eventOrigin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventOriginUpdateManyArgs>(args: Prisma.SelectSubset<T, EventOriginUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventOrigins and returns the data updated in the database.
   * @param {EventOriginUpdateManyAndReturnArgs} args - Arguments to update many EventOrigins.
   * @example
   * // Update many EventOrigins
   * const eventOrigin = await prisma.eventOrigin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventOrigins and only return the `id`
   * const eventOriginWithIdOnly = await prisma.eventOrigin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventOriginUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventOriginUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventOrigin.
   * @param {EventOriginUpsertArgs} args - Arguments to update or create a EventOrigin.
   * @example
   * // Update or create a EventOrigin
   * const eventOrigin = await prisma.eventOrigin.upsert({
   *   create: {
   *     // ... data to create a EventOrigin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventOrigin we want to update
   *   }
   * })
   */
  upsert<T extends EventOriginUpsertArgs>(args: Prisma.SelectSubset<T, EventOriginUpsertArgs<ExtArgs>>): Prisma.Prisma__EventOriginClient<runtime.Types.Result.GetResult<Prisma.$EventOriginPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventOrigins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginCountArgs} args - Arguments to filter EventOrigins to count.
   * @example
   * // Count the number of EventOrigins
   * const count = await prisma.eventOrigin.count({
   *   where: {
   *     // ... the filter for the EventOrigins we want to count
   *   }
   * })
  **/
  count<T extends EventOriginCountArgs>(
    args?: Prisma.Subset<T, EventOriginCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventOriginCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventOrigin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventOriginAggregateArgs>(args: Prisma.Subset<T, EventOriginAggregateArgs>): Prisma.PrismaPromise<GetEventOriginAggregateType<T>>

  /**
   * Group by EventOrigin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventOriginGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventOriginGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventOriginGroupByArgs['orderBy'] }
      : { orderBy?: EventOriginGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventOriginGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventOriginGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventOrigin model
 */
readonly fields: EventOriginFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventOrigin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventOriginClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  events<T extends Prisma.EventOrigin$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventOrigin$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventOrigin model
 */
export interface EventOriginFieldRefs {
  readonly id: Prisma.FieldRef<"EventOrigin", 'String'>
  readonly title: Prisma.FieldRef<"EventOrigin", 'String'>
  readonly description: Prisma.FieldRef<"EventOrigin", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventOrigin", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventOrigin", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventOrigin findUnique
 */
export type EventOriginFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter, which EventOrigin to fetch.
   */
  where: Prisma.EventOriginWhereUniqueInput
}

/**
 * EventOrigin findUniqueOrThrow
 */
export type EventOriginFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter, which EventOrigin to fetch.
   */
  where: Prisma.EventOriginWhereUniqueInput
}

/**
 * EventOrigin findFirst
 */
export type EventOriginFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter, which EventOrigin to fetch.
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventOrigins to fetch.
   */
  orderBy?: Prisma.EventOriginOrderByWithRelationInput | Prisma.EventOriginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventOrigins.
   */
  cursor?: Prisma.EventOriginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventOrigins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventOrigins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventOrigins.
   */
  distinct?: Prisma.EventOriginScalarFieldEnum | Prisma.EventOriginScalarFieldEnum[]
}

/**
 * EventOrigin findFirstOrThrow
 */
export type EventOriginFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter, which EventOrigin to fetch.
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventOrigins to fetch.
   */
  orderBy?: Prisma.EventOriginOrderByWithRelationInput | Prisma.EventOriginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventOrigins.
   */
  cursor?: Prisma.EventOriginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventOrigins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventOrigins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventOrigins.
   */
  distinct?: Prisma.EventOriginScalarFieldEnum | Prisma.EventOriginScalarFieldEnum[]
}

/**
 * EventOrigin findMany
 */
export type EventOriginFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter, which EventOrigins to fetch.
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventOrigins to fetch.
   */
  orderBy?: Prisma.EventOriginOrderByWithRelationInput | Prisma.EventOriginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventOrigins.
   */
  cursor?: Prisma.EventOriginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventOrigins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventOrigins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventOrigins.
   */
  distinct?: Prisma.EventOriginScalarFieldEnum | Prisma.EventOriginScalarFieldEnum[]
}

/**
 * EventOrigin create
 */
export type EventOriginCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * The data needed to create a EventOrigin.
   */
  data: Prisma.XOR<Prisma.EventOriginCreateInput, Prisma.EventOriginUncheckedCreateInput>
}

/**
 * EventOrigin createMany
 */
export type EventOriginCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventOrigins.
   */
  data: Prisma.EventOriginCreateManyInput | Prisma.EventOriginCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventOrigin createManyAndReturn
 */
export type EventOriginCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * The data used to create many EventOrigins.
   */
  data: Prisma.EventOriginCreateManyInput | Prisma.EventOriginCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventOrigin update
 */
export type EventOriginUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * The data needed to update a EventOrigin.
   */
  data: Prisma.XOR<Prisma.EventOriginUpdateInput, Prisma.EventOriginUncheckedUpdateInput>
  /**
   * Choose, which EventOrigin to update.
   */
  where: Prisma.EventOriginWhereUniqueInput
}

/**
 * EventOrigin updateMany
 */
export type EventOriginUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventOrigins.
   */
  data: Prisma.XOR<Prisma.EventOriginUpdateManyMutationInput, Prisma.EventOriginUncheckedUpdateManyInput>
  /**
   * Filter which EventOrigins to update
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * Limit how many EventOrigins to update.
   */
  limit?: number
}

/**
 * EventOrigin updateManyAndReturn
 */
export type EventOriginUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * The data used to update EventOrigins.
   */
  data: Prisma.XOR<Prisma.EventOriginUpdateManyMutationInput, Prisma.EventOriginUncheckedUpdateManyInput>
  /**
   * Filter which EventOrigins to update
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * Limit how many EventOrigins to update.
   */
  limit?: number
}

/**
 * EventOrigin upsert
 */
export type EventOriginUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * The filter to search for the EventOrigin to update in case it exists.
   */
  where: Prisma.EventOriginWhereUniqueInput
  /**
   * In case the EventOrigin found by the `where` argument doesn't exist, create a new EventOrigin with this data.
   */
  create: Prisma.XOR<Prisma.EventOriginCreateInput, Prisma.EventOriginUncheckedCreateInput>
  /**
   * In case the EventOrigin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventOriginUpdateInput, Prisma.EventOriginUncheckedUpdateInput>
}

/**
 * EventOrigin delete
 */
export type EventOriginDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
  /**
   * Filter which EventOrigin to delete.
   */
  where: Prisma.EventOriginWhereUniqueInput
}

/**
 * EventOrigin deleteMany
 */
export type EventOriginDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventOrigins to delete
   */
  where?: Prisma.EventOriginWhereInput
  /**
   * Limit how many EventOrigins to delete.
   */
  limit?: number
}

/**
 * EventOrigin.events
 */
export type EventOrigin$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Event
   */
  select?: Prisma.EventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Event
   */
  omit?: Prisma.EventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventInclude<ExtArgs> | null
  where?: Prisma.EventWhereInput
  orderBy?: Prisma.EventOrderByWithRelationInput | Prisma.EventOrderByWithRelationInput[]
  cursor?: Prisma.EventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventScalarFieldEnum | Prisma.EventScalarFieldEnum[]
}

/**
 * EventOrigin without action
 */
export type EventOriginDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventOrigin
   */
  select?: Prisma.EventOriginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventOrigin
   */
  omit?: Prisma.EventOriginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventOriginInclude<ExtArgs> | null
}
