
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MentorTechnicalArea` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MentorTechnicalArea
 * 
 */
export type MentorTechnicalAreaModel = runtime.Types.Result.DefaultSelection<Prisma.$MentorTechnicalAreaPayload>

export type AggregateMentorTechnicalArea = {
  _count: MentorTechnicalAreaCountAggregateOutputType | null
  _min: MentorTechnicalAreaMinAggregateOutputType | null
  _max: MentorTechnicalAreaMaxAggregateOutputType | null
}

export type MentorTechnicalAreaMinAggregateOutputType = {
  id: string | null
  mentorId: string | null
  technicalAreaId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MentorTechnicalAreaMaxAggregateOutputType = {
  id: string | null
  mentorId: string | null
  technicalAreaId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MentorTechnicalAreaCountAggregateOutputType = {
  id: number
  mentorId: number
  technicalAreaId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MentorTechnicalAreaMinAggregateInputType = {
  id?: true
  mentorId?: true
  technicalAreaId?: true
  createdAt?: true
  updatedAt?: true
}

export type MentorTechnicalAreaMaxAggregateInputType = {
  id?: true
  mentorId?: true
  technicalAreaId?: true
  createdAt?: true
  updatedAt?: true
}

export type MentorTechnicalAreaCountAggregateInputType = {
  id?: true
  mentorId?: true
  technicalAreaId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MentorTechnicalAreaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MentorTechnicalArea to aggregate.
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MentorTechnicalAreas to fetch.
   */
  orderBy?: Prisma.MentorTechnicalAreaOrderByWithRelationInput | Prisma.MentorTechnicalAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MentorTechnicalAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MentorTechnicalAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MentorTechnicalAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MentorTechnicalAreas
  **/
  _count?: true | MentorTechnicalAreaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MentorTechnicalAreaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MentorTechnicalAreaMaxAggregateInputType
}

export type GetMentorTechnicalAreaAggregateType<T extends MentorTechnicalAreaAggregateArgs> = {
      [P in keyof T & keyof AggregateMentorTechnicalArea]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMentorTechnicalArea[P]>
    : Prisma.GetScalarType<T[P], AggregateMentorTechnicalArea[P]>
}




export type MentorTechnicalAreaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MentorTechnicalAreaWhereInput
  orderBy?: Prisma.MentorTechnicalAreaOrderByWithAggregationInput | Prisma.MentorTechnicalAreaOrderByWithAggregationInput[]
  by: Prisma.MentorTechnicalAreaScalarFieldEnum[] | Prisma.MentorTechnicalAreaScalarFieldEnum
  having?: Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MentorTechnicalAreaCountAggregateInputType | true
  _min?: MentorTechnicalAreaMinAggregateInputType
  _max?: MentorTechnicalAreaMaxAggregateInputType
}

export type MentorTechnicalAreaGroupByOutputType = {
  id: string
  mentorId: string
  technicalAreaId: string
  createdAt: Date
  updatedAt: Date
  _count: MentorTechnicalAreaCountAggregateOutputType | null
  _min: MentorTechnicalAreaMinAggregateOutputType | null
  _max: MentorTechnicalAreaMaxAggregateOutputType | null
}

export type GetMentorTechnicalAreaGroupByPayload<T extends MentorTechnicalAreaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MentorTechnicalAreaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MentorTechnicalAreaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MentorTechnicalAreaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MentorTechnicalAreaGroupByOutputType[P]>
      }
    >
  >



export type MentorTechnicalAreaWhereInput = {
  AND?: Prisma.MentorTechnicalAreaWhereInput | Prisma.MentorTechnicalAreaWhereInput[]
  OR?: Prisma.MentorTechnicalAreaWhereInput[]
  NOT?: Prisma.MentorTechnicalAreaWhereInput | Prisma.MentorTechnicalAreaWhereInput[]
  id?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  mentorId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  technicalAreaId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  createdAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
  mentor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  technicalArea?: Prisma.XOR<Prisma.TechnicalAreaScalarRelationFilter, Prisma.TechnicalAreaWhereInput>
}

export type MentorTechnicalAreaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  technicalAreaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mentor?: Prisma.UserOrderByWithRelationInput
  technicalArea?: Prisma.TechnicalAreaOrderByWithRelationInput
}

export type MentorTechnicalAreaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  mentorId_technicalAreaId?: Prisma.MentorTechnicalAreaMentorIdTechnicalAreaIdCompoundUniqueInput
  AND?: Prisma.MentorTechnicalAreaWhereInput | Prisma.MentorTechnicalAreaWhereInput[]
  OR?: Prisma.MentorTechnicalAreaWhereInput[]
  NOT?: Prisma.MentorTechnicalAreaWhereInput | Prisma.MentorTechnicalAreaWhereInput[]
  mentorId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  technicalAreaId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  createdAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
  mentor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  technicalArea?: Prisma.XOR<Prisma.TechnicalAreaScalarRelationFilter, Prisma.TechnicalAreaWhereInput>
}, "id" | "mentorId_technicalAreaId">

export type MentorTechnicalAreaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  technicalAreaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MentorTechnicalAreaCountOrderByAggregateInput
  _max?: Prisma.MentorTechnicalAreaMaxOrderByAggregateInput
  _min?: Prisma.MentorTechnicalAreaMinOrderByAggregateInput
}

export type MentorTechnicalAreaScalarWhereWithAggregatesInput = {
  AND?: Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput | Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput[]
  OR?: Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput | Prisma.MentorTechnicalAreaScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MentorTechnicalArea"> | string
  mentorId?: Prisma.UuidWithAggregatesFilter<"MentorTechnicalArea"> | string
  technicalAreaId?: Prisma.UuidWithAggregatesFilter<"MentorTechnicalArea"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MentorTechnicalArea"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MentorTechnicalArea"> | Date | string
}

export type MentorTechnicalAreaCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mentor: Prisma.UserCreateNestedOneWithoutMentorTechnicalAreasInput
  technicalArea: Prisma.TechnicalAreaCreateNestedOneWithoutMentorsInput
}

export type MentorTechnicalAreaUncheckedCreateInput = {
  id?: string
  mentorId: string
  technicalAreaId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentor?: Prisma.UserUpdateOneRequiredWithoutMentorTechnicalAreasNestedInput
  technicalArea?: Prisma.TechnicalAreaUpdateOneRequiredWithoutMentorsNestedInput
}

export type MentorTechnicalAreaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  technicalAreaId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaCreateManyInput = {
  id?: string
  mentorId: string
  technicalAreaId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  technicalAreaId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaListRelationFilter = {
  every?: Prisma.MentorTechnicalAreaWhereInput
  some?: Prisma.MentorTechnicalAreaWhereInput
  none?: Prisma.MentorTechnicalAreaWhereInput
}

export type MentorTechnicalAreaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MentorTechnicalAreaMentorIdTechnicalAreaIdCompoundUniqueInput = {
  mentorId: string
  technicalAreaId: string
}

export type MentorTechnicalAreaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  technicalAreaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MentorTechnicalAreaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  technicalAreaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MentorTechnicalAreaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mentorId?: Prisma.SortOrder
  technicalAreaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MentorTechnicalAreaCreateNestedManyWithoutMentorInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput> | Prisma.MentorTechnicalAreaCreateWithoutMentorInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyMentorInputEnvelope
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
}

export type MentorTechnicalAreaUncheckedCreateNestedManyWithoutMentorInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput> | Prisma.MentorTechnicalAreaCreateWithoutMentorInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyMentorInputEnvelope
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
}

export type MentorTechnicalAreaUpdateManyWithoutMentorNestedInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput> | Prisma.MentorTechnicalAreaCreateWithoutMentorInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput[]
  upsert?: Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutMentorInput | Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutMentorInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyMentorInputEnvelope
  set?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  disconnect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  delete?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  update?: Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutMentorInput | Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutMentorInput[]
  updateMany?: Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutMentorInput | Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutMentorInput[]
  deleteMany?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
}

export type MentorTechnicalAreaUncheckedUpdateManyWithoutMentorNestedInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput> | Prisma.MentorTechnicalAreaCreateWithoutMentorInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutMentorInput[]
  upsert?: Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutMentorInput | Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutMentorInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyMentorInputEnvelope
  set?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  disconnect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  delete?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  update?: Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutMentorInput | Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutMentorInput[]
  updateMany?: Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutMentorInput | Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutMentorInput[]
  deleteMany?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
}

export type MentorTechnicalAreaCreateNestedManyWithoutTechnicalAreaInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput> | Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInputEnvelope
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
}

export type MentorTechnicalAreaUncheckedCreateNestedManyWithoutTechnicalAreaInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput> | Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInputEnvelope
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
}

export type MentorTechnicalAreaUpdateManyWithoutTechnicalAreaNestedInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput> | Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput[]
  upsert?: Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutTechnicalAreaInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInputEnvelope
  set?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  disconnect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  delete?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  update?: Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutTechnicalAreaInput[]
  updateMany?: Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutTechnicalAreaInput[]
  deleteMany?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
}

export type MentorTechnicalAreaUncheckedUpdateManyWithoutTechnicalAreaNestedInput = {
  create?: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput> | Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput[] | Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput[]
  connectOrCreate?: Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput[]
  upsert?: Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpsertWithWhereUniqueWithoutTechnicalAreaInput[]
  createMany?: Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInputEnvelope
  set?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  disconnect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  delete?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  connect?: Prisma.MentorTechnicalAreaWhereUniqueInput | Prisma.MentorTechnicalAreaWhereUniqueInput[]
  update?: Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpdateWithWhereUniqueWithoutTechnicalAreaInput[]
  updateMany?: Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutTechnicalAreaInput | Prisma.MentorTechnicalAreaUpdateManyWithWhereWithoutTechnicalAreaInput[]
  deleteMany?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
}

export type MentorTechnicalAreaCreateWithoutMentorInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  technicalArea: Prisma.TechnicalAreaCreateNestedOneWithoutMentorsInput
}

export type MentorTechnicalAreaUncheckedCreateWithoutMentorInput = {
  id?: string
  technicalAreaId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaCreateOrConnectWithoutMentorInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  create: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput>
}

export type MentorTechnicalAreaCreateManyMentorInputEnvelope = {
  data: Prisma.MentorTechnicalAreaCreateManyMentorInput | Prisma.MentorTechnicalAreaCreateManyMentorInput[]
  skipDuplicates?: boolean
}

export type MentorTechnicalAreaUpsertWithWhereUniqueWithoutMentorInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  update: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedUpdateWithoutMentorInput>
  create: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutMentorInput>
}

export type MentorTechnicalAreaUpdateWithWhereUniqueWithoutMentorInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateWithoutMentorInput, Prisma.MentorTechnicalAreaUncheckedUpdateWithoutMentorInput>
}

export type MentorTechnicalAreaUpdateManyWithWhereWithoutMentorInput = {
  where: Prisma.MentorTechnicalAreaScalarWhereInput
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateManyMutationInput, Prisma.MentorTechnicalAreaUncheckedUpdateManyWithoutMentorInput>
}

export type MentorTechnicalAreaScalarWhereInput = {
  AND?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
  OR?: Prisma.MentorTechnicalAreaScalarWhereInput[]
  NOT?: Prisma.MentorTechnicalAreaScalarWhereInput | Prisma.MentorTechnicalAreaScalarWhereInput[]
  id?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  mentorId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  technicalAreaId?: Prisma.UuidFilter<"MentorTechnicalArea"> | string
  createdAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MentorTechnicalArea"> | Date | string
}

export type MentorTechnicalAreaCreateWithoutTechnicalAreaInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mentor: Prisma.UserCreateNestedOneWithoutMentorTechnicalAreasInput
}

export type MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput = {
  id?: string
  mentorId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaCreateOrConnectWithoutTechnicalAreaInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  create: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput>
}

export type MentorTechnicalAreaCreateManyTechnicalAreaInputEnvelope = {
  data: Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInput | Prisma.MentorTechnicalAreaCreateManyTechnicalAreaInput[]
  skipDuplicates?: boolean
}

export type MentorTechnicalAreaUpsertWithWhereUniqueWithoutTechnicalAreaInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  update: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedUpdateWithoutTechnicalAreaInput>
  create: Prisma.XOR<Prisma.MentorTechnicalAreaCreateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedCreateWithoutTechnicalAreaInput>
}

export type MentorTechnicalAreaUpdateWithWhereUniqueWithoutTechnicalAreaInput = {
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateWithoutTechnicalAreaInput, Prisma.MentorTechnicalAreaUncheckedUpdateWithoutTechnicalAreaInput>
}

export type MentorTechnicalAreaUpdateManyWithWhereWithoutTechnicalAreaInput = {
  where: Prisma.MentorTechnicalAreaScalarWhereInput
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateManyMutationInput, Prisma.MentorTechnicalAreaUncheckedUpdateManyWithoutTechnicalAreaInput>
}

export type MentorTechnicalAreaCreateManyMentorInput = {
  id?: string
  technicalAreaId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaUpdateWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  technicalArea?: Prisma.TechnicalAreaUpdateOneRequiredWithoutMentorsNestedInput
}

export type MentorTechnicalAreaUncheckedUpdateWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  technicalAreaId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaUncheckedUpdateManyWithoutMentorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  technicalAreaId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaCreateManyTechnicalAreaInput = {
  id?: string
  mentorId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MentorTechnicalAreaUpdateWithoutTechnicalAreaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentor?: Prisma.UserUpdateOneRequiredWithoutMentorTechnicalAreasNestedInput
}

export type MentorTechnicalAreaUncheckedUpdateWithoutTechnicalAreaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MentorTechnicalAreaUncheckedUpdateManyWithoutTechnicalAreaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mentorId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MentorTechnicalAreaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  technicalAreaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mentorTechnicalArea"]>

export type MentorTechnicalAreaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  technicalAreaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mentorTechnicalArea"]>

export type MentorTechnicalAreaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mentorId?: boolean
  technicalAreaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mentorTechnicalArea"]>

export type MentorTechnicalAreaSelectScalar = {
  id?: boolean
  mentorId?: boolean
  technicalAreaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MentorTechnicalAreaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mentorId" | "technicalAreaId" | "createdAt" | "updatedAt", ExtArgs["result"]["mentorTechnicalArea"]>
export type MentorTechnicalAreaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}
export type MentorTechnicalAreaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}
export type MentorTechnicalAreaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  technicalArea?: boolean | Prisma.TechnicalAreaDefaultArgs<ExtArgs>
}

export type $MentorTechnicalAreaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MentorTechnicalArea"
  objects: {
    mentor: Prisma.$UserPayload<ExtArgs>
    technicalArea: Prisma.$TechnicalAreaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mentorId: string
    technicalAreaId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["mentorTechnicalArea"]>
  composites: {}
}

export type MentorTechnicalAreaGetPayload<S extends boolean | null | undefined | MentorTechnicalAreaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload, S>

export type MentorTechnicalAreaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MentorTechnicalAreaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MentorTechnicalAreaCountAggregateInputType | true
  }

export interface MentorTechnicalAreaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MentorTechnicalArea'], meta: { name: 'MentorTechnicalArea' } }
  /**
   * Find zero or one MentorTechnicalArea that matches the filter.
   * @param {MentorTechnicalAreaFindUniqueArgs} args - Arguments to find a MentorTechnicalArea
   * @example
   * // Get one MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MentorTechnicalAreaFindUniqueArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MentorTechnicalArea that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MentorTechnicalAreaFindUniqueOrThrowArgs} args - Arguments to find a MentorTechnicalArea
   * @example
   * // Get one MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MentorTechnicalAreaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MentorTechnicalArea that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaFindFirstArgs} args - Arguments to find a MentorTechnicalArea
   * @example
   * // Get one MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MentorTechnicalAreaFindFirstArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaFindFirstArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MentorTechnicalArea that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaFindFirstOrThrowArgs} args - Arguments to find a MentorTechnicalArea
   * @example
   * // Get one MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MentorTechnicalAreaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MentorTechnicalAreas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MentorTechnicalAreas
   * const mentorTechnicalAreas = await prisma.mentorTechnicalArea.findMany()
   * 
   * // Get first 10 MentorTechnicalAreas
   * const mentorTechnicalAreas = await prisma.mentorTechnicalArea.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mentorTechnicalAreaWithIdOnly = await prisma.mentorTechnicalArea.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MentorTechnicalAreaFindManyArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MentorTechnicalArea.
   * @param {MentorTechnicalAreaCreateArgs} args - Arguments to create a MentorTechnicalArea.
   * @example
   * // Create one MentorTechnicalArea
   * const MentorTechnicalArea = await prisma.mentorTechnicalArea.create({
   *   data: {
   *     // ... data to create a MentorTechnicalArea
   *   }
   * })
   * 
   */
  create<T extends MentorTechnicalAreaCreateArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaCreateArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MentorTechnicalAreas.
   * @param {MentorTechnicalAreaCreateManyArgs} args - Arguments to create many MentorTechnicalAreas.
   * @example
   * // Create many MentorTechnicalAreas
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MentorTechnicalAreaCreateManyArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MentorTechnicalAreas and returns the data saved in the database.
   * @param {MentorTechnicalAreaCreateManyAndReturnArgs} args - Arguments to create many MentorTechnicalAreas.
   * @example
   * // Create many MentorTechnicalAreas
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MentorTechnicalAreas and only return the `id`
   * const mentorTechnicalAreaWithIdOnly = await prisma.mentorTechnicalArea.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MentorTechnicalAreaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MentorTechnicalArea.
   * @param {MentorTechnicalAreaDeleteArgs} args - Arguments to delete one MentorTechnicalArea.
   * @example
   * // Delete one MentorTechnicalArea
   * const MentorTechnicalArea = await prisma.mentorTechnicalArea.delete({
   *   where: {
   *     // ... filter to delete one MentorTechnicalArea
   *   }
   * })
   * 
   */
  delete<T extends MentorTechnicalAreaDeleteArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaDeleteArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MentorTechnicalArea.
   * @param {MentorTechnicalAreaUpdateArgs} args - Arguments to update one MentorTechnicalArea.
   * @example
   * // Update one MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MentorTechnicalAreaUpdateArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaUpdateArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MentorTechnicalAreas.
   * @param {MentorTechnicalAreaDeleteManyArgs} args - Arguments to filter MentorTechnicalAreas to delete.
   * @example
   * // Delete a few MentorTechnicalAreas
   * const { count } = await prisma.mentorTechnicalArea.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MentorTechnicalAreaDeleteManyArgs>(args?: Prisma.SelectSubset<T, MentorTechnicalAreaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MentorTechnicalAreas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MentorTechnicalAreas
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MentorTechnicalAreaUpdateManyArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MentorTechnicalAreas and returns the data updated in the database.
   * @param {MentorTechnicalAreaUpdateManyAndReturnArgs} args - Arguments to update many MentorTechnicalAreas.
   * @example
   * // Update many MentorTechnicalAreas
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MentorTechnicalAreas and only return the `id`
   * const mentorTechnicalAreaWithIdOnly = await prisma.mentorTechnicalArea.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MentorTechnicalAreaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MentorTechnicalArea.
   * @param {MentorTechnicalAreaUpsertArgs} args - Arguments to update or create a MentorTechnicalArea.
   * @example
   * // Update or create a MentorTechnicalArea
   * const mentorTechnicalArea = await prisma.mentorTechnicalArea.upsert({
   *   create: {
   *     // ... data to create a MentorTechnicalArea
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MentorTechnicalArea we want to update
   *   }
   * })
   */
  upsert<T extends MentorTechnicalAreaUpsertArgs>(args: Prisma.SelectSubset<T, MentorTechnicalAreaUpsertArgs<ExtArgs>>): Prisma.Prisma__MentorTechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$MentorTechnicalAreaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MentorTechnicalAreas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaCountArgs} args - Arguments to filter MentorTechnicalAreas to count.
   * @example
   * // Count the number of MentorTechnicalAreas
   * const count = await prisma.mentorTechnicalArea.count({
   *   where: {
   *     // ... the filter for the MentorTechnicalAreas we want to count
   *   }
   * })
  **/
  count<T extends MentorTechnicalAreaCountArgs>(
    args?: Prisma.Subset<T, MentorTechnicalAreaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MentorTechnicalAreaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MentorTechnicalArea.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MentorTechnicalAreaAggregateArgs>(args: Prisma.Subset<T, MentorTechnicalAreaAggregateArgs>): Prisma.PrismaPromise<GetMentorTechnicalAreaAggregateType<T>>

  /**
   * Group by MentorTechnicalArea.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentorTechnicalAreaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MentorTechnicalAreaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MentorTechnicalAreaGroupByArgs['orderBy'] }
      : { orderBy?: MentorTechnicalAreaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MentorTechnicalAreaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMentorTechnicalAreaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MentorTechnicalArea model
 */
readonly fields: MentorTechnicalAreaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MentorTechnicalArea.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MentorTechnicalAreaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mentor<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  technicalArea<T extends Prisma.TechnicalAreaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechnicalAreaDefaultArgs<ExtArgs>>): Prisma.Prisma__TechnicalAreaClient<runtime.Types.Result.GetResult<Prisma.$TechnicalAreaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MentorTechnicalArea model
 */
export interface MentorTechnicalAreaFieldRefs {
  readonly id: Prisma.FieldRef<"MentorTechnicalArea", 'String'>
  readonly mentorId: Prisma.FieldRef<"MentorTechnicalArea", 'String'>
  readonly technicalAreaId: Prisma.FieldRef<"MentorTechnicalArea", 'String'>
  readonly createdAt: Prisma.FieldRef<"MentorTechnicalArea", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MentorTechnicalArea", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MentorTechnicalArea findUnique
 */
export type MentorTechnicalAreaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter, which MentorTechnicalArea to fetch.
   */
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
}

/**
 * MentorTechnicalArea findUniqueOrThrow
 */
export type MentorTechnicalAreaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter, which MentorTechnicalArea to fetch.
   */
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
}

/**
 * MentorTechnicalArea findFirst
 */
export type MentorTechnicalAreaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter, which MentorTechnicalArea to fetch.
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MentorTechnicalAreas to fetch.
   */
  orderBy?: Prisma.MentorTechnicalAreaOrderByWithRelationInput | Prisma.MentorTechnicalAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MentorTechnicalAreas.
   */
  cursor?: Prisma.MentorTechnicalAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MentorTechnicalAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MentorTechnicalAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MentorTechnicalAreas.
   */
  distinct?: Prisma.MentorTechnicalAreaScalarFieldEnum | Prisma.MentorTechnicalAreaScalarFieldEnum[]
}

/**
 * MentorTechnicalArea findFirstOrThrow
 */
export type MentorTechnicalAreaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter, which MentorTechnicalArea to fetch.
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MentorTechnicalAreas to fetch.
   */
  orderBy?: Prisma.MentorTechnicalAreaOrderByWithRelationInput | Prisma.MentorTechnicalAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MentorTechnicalAreas.
   */
  cursor?: Prisma.MentorTechnicalAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MentorTechnicalAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MentorTechnicalAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MentorTechnicalAreas.
   */
  distinct?: Prisma.MentorTechnicalAreaScalarFieldEnum | Prisma.MentorTechnicalAreaScalarFieldEnum[]
}

/**
 * MentorTechnicalArea findMany
 */
export type MentorTechnicalAreaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter, which MentorTechnicalAreas to fetch.
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MentorTechnicalAreas to fetch.
   */
  orderBy?: Prisma.MentorTechnicalAreaOrderByWithRelationInput | Prisma.MentorTechnicalAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MentorTechnicalAreas.
   */
  cursor?: Prisma.MentorTechnicalAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MentorTechnicalAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MentorTechnicalAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MentorTechnicalAreas.
   */
  distinct?: Prisma.MentorTechnicalAreaScalarFieldEnum | Prisma.MentorTechnicalAreaScalarFieldEnum[]
}

/**
 * MentorTechnicalArea create
 */
export type MentorTechnicalAreaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * The data needed to create a MentorTechnicalArea.
   */
  data: Prisma.XOR<Prisma.MentorTechnicalAreaCreateInput, Prisma.MentorTechnicalAreaUncheckedCreateInput>
}

/**
 * MentorTechnicalArea createMany
 */
export type MentorTechnicalAreaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MentorTechnicalAreas.
   */
  data: Prisma.MentorTechnicalAreaCreateManyInput | Prisma.MentorTechnicalAreaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MentorTechnicalArea createManyAndReturn
 */
export type MentorTechnicalAreaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * The data used to create many MentorTechnicalAreas.
   */
  data: Prisma.MentorTechnicalAreaCreateManyInput | Prisma.MentorTechnicalAreaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MentorTechnicalArea update
 */
export type MentorTechnicalAreaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * The data needed to update a MentorTechnicalArea.
   */
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateInput, Prisma.MentorTechnicalAreaUncheckedUpdateInput>
  /**
   * Choose, which MentorTechnicalArea to update.
   */
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
}

/**
 * MentorTechnicalArea updateMany
 */
export type MentorTechnicalAreaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MentorTechnicalAreas.
   */
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateManyMutationInput, Prisma.MentorTechnicalAreaUncheckedUpdateManyInput>
  /**
   * Filter which MentorTechnicalAreas to update
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * Limit how many MentorTechnicalAreas to update.
   */
  limit?: number
}

/**
 * MentorTechnicalArea updateManyAndReturn
 */
export type MentorTechnicalAreaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * The data used to update MentorTechnicalAreas.
   */
  data: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateManyMutationInput, Prisma.MentorTechnicalAreaUncheckedUpdateManyInput>
  /**
   * Filter which MentorTechnicalAreas to update
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * Limit how many MentorTechnicalAreas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MentorTechnicalArea upsert
 */
export type MentorTechnicalAreaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * The filter to search for the MentorTechnicalArea to update in case it exists.
   */
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
  /**
   * In case the MentorTechnicalArea found by the `where` argument doesn't exist, create a new MentorTechnicalArea with this data.
   */
  create: Prisma.XOR<Prisma.MentorTechnicalAreaCreateInput, Prisma.MentorTechnicalAreaUncheckedCreateInput>
  /**
   * In case the MentorTechnicalArea was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MentorTechnicalAreaUpdateInput, Prisma.MentorTechnicalAreaUncheckedUpdateInput>
}

/**
 * MentorTechnicalArea delete
 */
export type MentorTechnicalAreaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
  /**
   * Filter which MentorTechnicalArea to delete.
   */
  where: Prisma.MentorTechnicalAreaWhereUniqueInput
}

/**
 * MentorTechnicalArea deleteMany
 */
export type MentorTechnicalAreaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MentorTechnicalAreas to delete
   */
  where?: Prisma.MentorTechnicalAreaWhereInput
  /**
   * Limit how many MentorTechnicalAreas to delete.
   */
  limit?: number
}

/**
 * MentorTechnicalArea without action
 */
export type MentorTechnicalAreaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorTechnicalArea
   */
  select?: Prisma.MentorTechnicalAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorTechnicalArea
   */
  omit?: Prisma.MentorTechnicalAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorTechnicalAreaInclude<ExtArgs> | null
}
