
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrientationType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model OrientationType
 * 
 */
export type OrientationTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$OrientationTypePayload>

export type AggregateOrientationType = {
  _count: OrientationTypeCountAggregateOutputType | null
  _min: OrientationTypeMinAggregateOutputType | null
  _max: OrientationTypeMaxAggregateOutputType | null
}

export type OrientationTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrientationTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrientationTypeCountAggregateOutputType = {
  id: number
  name: number
  description: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrientationTypeMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type OrientationTypeMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type OrientationTypeCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrientationTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrientationType to aggregate.
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrientationTypes to fetch.
   */
  orderBy?: Prisma.OrientationTypeOrderByWithRelationInput | Prisma.OrientationTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrientationTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrientationTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrientationTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrientationTypes
  **/
  _count?: true | OrientationTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrientationTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrientationTypeMaxAggregateInputType
}

export type GetOrientationTypeAggregateType<T extends OrientationTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateOrientationType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrientationType[P]>
    : Prisma.GetScalarType<T[P], AggregateOrientationType[P]>
}




export type OrientationTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrientationTypeWhereInput
  orderBy?: Prisma.OrientationTypeOrderByWithAggregationInput | Prisma.OrientationTypeOrderByWithAggregationInput[]
  by: Prisma.OrientationTypeScalarFieldEnum[] | Prisma.OrientationTypeScalarFieldEnum
  having?: Prisma.OrientationTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrientationTypeCountAggregateInputType | true
  _min?: OrientationTypeMinAggregateInputType
  _max?: OrientationTypeMaxAggregateInputType
}

export type OrientationTypeGroupByOutputType = {
  id: string
  name: string
  description: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: OrientationTypeCountAggregateOutputType | null
  _min: OrientationTypeMinAggregateOutputType | null
  _max: OrientationTypeMaxAggregateOutputType | null
}

export type GetOrientationTypeGroupByPayload<T extends OrientationTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrientationTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrientationTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrientationTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrientationTypeGroupByOutputType[P]>
      }
    >
  >



export type OrientationTypeWhereInput = {
  AND?: Prisma.OrientationTypeWhereInput | Prisma.OrientationTypeWhereInput[]
  OR?: Prisma.OrientationTypeWhereInput[]
  NOT?: Prisma.OrientationTypeWhereInput | Prisma.OrientationTypeWhereInput[]
  id?: Prisma.UuidFilter<"OrientationType"> | string
  name?: Prisma.StringFilter<"OrientationType"> | string
  description?: Prisma.StringNullableFilter<"OrientationType"> | string | null
  isActive?: Prisma.BoolFilter<"OrientationType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"OrientationType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrientationType"> | Date | string
  mentors?: Prisma.MentorOrientationTypeListRelationFilter
  appointments?: Prisma.AppointmentListRelationFilter
}

export type OrientationTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mentors?: Prisma.MentorOrientationTypeOrderByRelationAggregateInput
  appointments?: Prisma.AppointmentOrderByRelationAggregateInput
}

export type OrientationTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.OrientationTypeWhereInput | Prisma.OrientationTypeWhereInput[]
  OR?: Prisma.OrientationTypeWhereInput[]
  NOT?: Prisma.OrientationTypeWhereInput | Prisma.OrientationTypeWhereInput[]
  description?: Prisma.StringNullableFilter<"OrientationType"> | string | null
  isActive?: Prisma.BoolFilter<"OrientationType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"OrientationType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrientationType"> | Date | string
  mentors?: Prisma.MentorOrientationTypeListRelationFilter
  appointments?: Prisma.AppointmentListRelationFilter
}, "id" | "name">

export type OrientationTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrientationTypeCountOrderByAggregateInput
  _max?: Prisma.OrientationTypeMaxOrderByAggregateInput
  _min?: Prisma.OrientationTypeMinOrderByAggregateInput
}

export type OrientationTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrientationTypeScalarWhereWithAggregatesInput | Prisma.OrientationTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrientationTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrientationTypeScalarWhereWithAggregatesInput | Prisma.OrientationTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"OrientationType"> | string
  name?: Prisma.StringWithAggregatesFilter<"OrientationType"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"OrientationType"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"OrientationType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrientationType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OrientationType"> | Date | string
}

export type OrientationTypeCreateInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mentors?: Prisma.MentorOrientationTypeCreateNestedManyWithoutOrientationTypeInput
  appointments?: Prisma.AppointmentCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mentors?: Prisma.MentorOrientationTypeUncheckedCreateNestedManyWithoutOrientationTypeInput
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentors?: Prisma.MentorOrientationTypeUpdateManyWithoutOrientationTypeNestedInput
  appointments?: Prisma.AppointmentUpdateManyWithoutOrientationTypeNestedInput
}

export type OrientationTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentors?: Prisma.MentorOrientationTypeUncheckedUpdateManyWithoutOrientationTypeNestedInput
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutOrientationTypeNestedInput
}

export type OrientationTypeCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrientationTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrientationTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrientationTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrientationTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrientationTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrientationTypeScalarRelationFilter = {
  is?: Prisma.OrientationTypeWhereInput
  isNot?: Prisma.OrientationTypeWhereInput
}

export type OrientationTypeNullableScalarRelationFilter = {
  is?: Prisma.OrientationTypeWhereInput | null
  isNot?: Prisma.OrientationTypeWhereInput | null
}

export type OrientationTypeCreateNestedOneWithoutMentorsInput = {
  create?: Prisma.XOR<Prisma.OrientationTypeCreateWithoutMentorsInput, Prisma.OrientationTypeUncheckedCreateWithoutMentorsInput>
  connectOrCreate?: Prisma.OrientationTypeCreateOrConnectWithoutMentorsInput
  connect?: Prisma.OrientationTypeWhereUniqueInput
}

export type OrientationTypeUpdateOneRequiredWithoutMentorsNestedInput = {
  create?: Prisma.XOR<Prisma.OrientationTypeCreateWithoutMentorsInput, Prisma.OrientationTypeUncheckedCreateWithoutMentorsInput>
  connectOrCreate?: Prisma.OrientationTypeCreateOrConnectWithoutMentorsInput
  upsert?: Prisma.OrientationTypeUpsertWithoutMentorsInput
  connect?: Prisma.OrientationTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrientationTypeUpdateToOneWithWhereWithoutMentorsInput, Prisma.OrientationTypeUpdateWithoutMentorsInput>, Prisma.OrientationTypeUncheckedUpdateWithoutMentorsInput>
}

export type OrientationTypeCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.OrientationTypeCreateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.OrientationTypeCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.OrientationTypeWhereUniqueInput
}

export type OrientationTypeUpdateOneWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.OrientationTypeCreateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.OrientationTypeCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.OrientationTypeUpsertWithoutAppointmentsInput
  disconnect?: Prisma.OrientationTypeWhereInput | boolean
  delete?: Prisma.OrientationTypeWhereInput | boolean
  connect?: Prisma.OrientationTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrientationTypeUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.OrientationTypeUpdateWithoutAppointmentsInput>, Prisma.OrientationTypeUncheckedUpdateWithoutAppointmentsInput>
}

export type OrientationTypeCreateWithoutMentorsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeUncheckedCreateWithoutMentorsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  appointments?: Prisma.AppointmentUncheckedCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeCreateOrConnectWithoutMentorsInput = {
  where: Prisma.OrientationTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.OrientationTypeCreateWithoutMentorsInput, Prisma.OrientationTypeUncheckedCreateWithoutMentorsInput>
}

export type OrientationTypeUpsertWithoutMentorsInput = {
  update: Prisma.XOR<Prisma.OrientationTypeUpdateWithoutMentorsInput, Prisma.OrientationTypeUncheckedUpdateWithoutMentorsInput>
  create: Prisma.XOR<Prisma.OrientationTypeCreateWithoutMentorsInput, Prisma.OrientationTypeUncheckedCreateWithoutMentorsInput>
  where?: Prisma.OrientationTypeWhereInput
}

export type OrientationTypeUpdateToOneWithWhereWithoutMentorsInput = {
  where?: Prisma.OrientationTypeWhereInput
  data: Prisma.XOR<Prisma.OrientationTypeUpdateWithoutMentorsInput, Prisma.OrientationTypeUncheckedUpdateWithoutMentorsInput>
}

export type OrientationTypeUpdateWithoutMentorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUpdateManyWithoutOrientationTypeNestedInput
}

export type OrientationTypeUncheckedUpdateWithoutMentorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.AppointmentUncheckedUpdateManyWithoutOrientationTypeNestedInput
}

export type OrientationTypeCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mentors?: Prisma.MentorOrientationTypeCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeUncheckedCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mentors?: Prisma.MentorOrientationTypeUncheckedCreateNestedManyWithoutOrientationTypeInput
}

export type OrientationTypeCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.OrientationTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.OrientationTypeCreateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedCreateWithoutAppointmentsInput>
}

export type OrientationTypeUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.OrientationTypeUpdateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.OrientationTypeCreateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.OrientationTypeWhereInput
}

export type OrientationTypeUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.OrientationTypeWhereInput
  data: Prisma.XOR<Prisma.OrientationTypeUpdateWithoutAppointmentsInput, Prisma.OrientationTypeUncheckedUpdateWithoutAppointmentsInput>
}

export type OrientationTypeUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentors?: Prisma.MentorOrientationTypeUpdateManyWithoutOrientationTypeNestedInput
}

export type OrientationTypeUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mentors?: Prisma.MentorOrientationTypeUncheckedUpdateManyWithoutOrientationTypeNestedInput
}


/**
 * Count Type OrientationTypeCountOutputType
 */

export type OrientationTypeCountOutputType = {
  mentors: number
  appointments: number
}

export type OrientationTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentors?: boolean | OrientationTypeCountOutputTypeCountMentorsArgs
  appointments?: boolean | OrientationTypeCountOutputTypeCountAppointmentsArgs
}

/**
 * OrientationTypeCountOutputType without action
 */
export type OrientationTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationTypeCountOutputType
   */
  select?: Prisma.OrientationTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrientationTypeCountOutputType without action
 */
export type OrientationTypeCountOutputTypeCountMentorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MentorOrientationTypeWhereInput
}

/**
 * OrientationTypeCountOutputType without action
 */
export type OrientationTypeCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
}


export type OrientationTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mentors?: boolean | Prisma.OrientationType$mentorsArgs<ExtArgs>
  appointments?: boolean | Prisma.OrientationType$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.OrientationTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orientationType"]>

export type OrientationTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["orientationType"]>

export type OrientationTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["orientationType"]>

export type OrientationTypeSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrientationTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["orientationType"]>
export type OrientationTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mentors?: boolean | Prisma.OrientationType$mentorsArgs<ExtArgs>
  appointments?: boolean | Prisma.OrientationType$appointmentsArgs<ExtArgs>
  _count?: boolean | Prisma.OrientationTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type OrientationTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type OrientationTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $OrientationTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrientationType"
  objects: {
    mentors: Prisma.$MentorOrientationTypePayload<ExtArgs>[]
    appointments: Prisma.$AppointmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["orientationType"]>
  composites: {}
}

export type OrientationTypeGetPayload<S extends boolean | null | undefined | OrientationTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload, S>

export type OrientationTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrientationTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrientationTypeCountAggregateInputType | true
  }

export interface OrientationTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrientationType'], meta: { name: 'OrientationType' } }
  /**
   * Find zero or one OrientationType that matches the filter.
   * @param {OrientationTypeFindUniqueArgs} args - Arguments to find a OrientationType
   * @example
   * // Get one OrientationType
   * const orientationType = await prisma.orientationType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrientationTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, OrientationTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrientationType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrientationTypeFindUniqueOrThrowArgs} args - Arguments to find a OrientationType
   * @example
   * // Get one OrientationType
   * const orientationType = await prisma.orientationType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrientationTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrientationTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrientationType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeFindFirstArgs} args - Arguments to find a OrientationType
   * @example
   * // Get one OrientationType
   * const orientationType = await prisma.orientationType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrientationTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, OrientationTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrientationType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeFindFirstOrThrowArgs} args - Arguments to find a OrientationType
   * @example
   * // Get one OrientationType
   * const orientationType = await prisma.orientationType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrientationTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrientationTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrientationTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrientationTypes
   * const orientationTypes = await prisma.orientationType.findMany()
   * 
   * // Get first 10 OrientationTypes
   * const orientationTypes = await prisma.orientationType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orientationTypeWithIdOnly = await prisma.orientationType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrientationTypeFindManyArgs>(args?: Prisma.SelectSubset<T, OrientationTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrientationType.
   * @param {OrientationTypeCreateArgs} args - Arguments to create a OrientationType.
   * @example
   * // Create one OrientationType
   * const OrientationType = await prisma.orientationType.create({
   *   data: {
   *     // ... data to create a OrientationType
   *   }
   * })
   * 
   */
  create<T extends OrientationTypeCreateArgs>(args: Prisma.SelectSubset<T, OrientationTypeCreateArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrientationTypes.
   * @param {OrientationTypeCreateManyArgs} args - Arguments to create many OrientationTypes.
   * @example
   * // Create many OrientationTypes
   * const orientationType = await prisma.orientationType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrientationTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, OrientationTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrientationTypes and returns the data saved in the database.
   * @param {OrientationTypeCreateManyAndReturnArgs} args - Arguments to create many OrientationTypes.
   * @example
   * // Create many OrientationTypes
   * const orientationType = await prisma.orientationType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrientationTypes and only return the `id`
   * const orientationTypeWithIdOnly = await prisma.orientationType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrientationTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrientationTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrientationType.
   * @param {OrientationTypeDeleteArgs} args - Arguments to delete one OrientationType.
   * @example
   * // Delete one OrientationType
   * const OrientationType = await prisma.orientationType.delete({
   *   where: {
   *     // ... filter to delete one OrientationType
   *   }
   * })
   * 
   */
  delete<T extends OrientationTypeDeleteArgs>(args: Prisma.SelectSubset<T, OrientationTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrientationType.
   * @param {OrientationTypeUpdateArgs} args - Arguments to update one OrientationType.
   * @example
   * // Update one OrientationType
   * const orientationType = await prisma.orientationType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrientationTypeUpdateArgs>(args: Prisma.SelectSubset<T, OrientationTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrientationTypes.
   * @param {OrientationTypeDeleteManyArgs} args - Arguments to filter OrientationTypes to delete.
   * @example
   * // Delete a few OrientationTypes
   * const { count } = await prisma.orientationType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrientationTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrientationTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrientationTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrientationTypes
   * const orientationType = await prisma.orientationType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrientationTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, OrientationTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrientationTypes and returns the data updated in the database.
   * @param {OrientationTypeUpdateManyAndReturnArgs} args - Arguments to update many OrientationTypes.
   * @example
   * // Update many OrientationTypes
   * const orientationType = await prisma.orientationType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrientationTypes and only return the `id`
   * const orientationTypeWithIdOnly = await prisma.orientationType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrientationTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrientationTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrientationType.
   * @param {OrientationTypeUpsertArgs} args - Arguments to update or create a OrientationType.
   * @example
   * // Update or create a OrientationType
   * const orientationType = await prisma.orientationType.upsert({
   *   create: {
   *     // ... data to create a OrientationType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrientationType we want to update
   *   }
   * })
   */
  upsert<T extends OrientationTypeUpsertArgs>(args: Prisma.SelectSubset<T, OrientationTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__OrientationTypeClient<runtime.Types.Result.GetResult<Prisma.$OrientationTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrientationTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeCountArgs} args - Arguments to filter OrientationTypes to count.
   * @example
   * // Count the number of OrientationTypes
   * const count = await prisma.orientationType.count({
   *   where: {
   *     // ... the filter for the OrientationTypes we want to count
   *   }
   * })
  **/
  count<T extends OrientationTypeCountArgs>(
    args?: Prisma.Subset<T, OrientationTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrientationTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrientationType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrientationTypeAggregateArgs>(args: Prisma.Subset<T, OrientationTypeAggregateArgs>): Prisma.PrismaPromise<GetOrientationTypeAggregateType<T>>

  /**
   * Group by OrientationType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrientationTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrientationTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrientationTypeGroupByArgs['orderBy'] }
      : { orderBy?: OrientationTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrientationTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrientationTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrientationType model
 */
readonly fields: OrientationTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrientationType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrientationTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mentors<T extends Prisma.OrientationType$mentorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrientationType$mentorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MentorOrientationTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  appointments<T extends Prisma.OrientationType$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrientationType$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrientationType model
 */
export interface OrientationTypeFieldRefs {
  readonly id: Prisma.FieldRef<"OrientationType", 'String'>
  readonly name: Prisma.FieldRef<"OrientationType", 'String'>
  readonly description: Prisma.FieldRef<"OrientationType", 'String'>
  readonly isActive: Prisma.FieldRef<"OrientationType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"OrientationType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OrientationType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrientationType findUnique
 */
export type OrientationTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter, which OrientationType to fetch.
   */
  where: Prisma.OrientationTypeWhereUniqueInput
}

/**
 * OrientationType findUniqueOrThrow
 */
export type OrientationTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter, which OrientationType to fetch.
   */
  where: Prisma.OrientationTypeWhereUniqueInput
}

/**
 * OrientationType findFirst
 */
export type OrientationTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter, which OrientationType to fetch.
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrientationTypes to fetch.
   */
  orderBy?: Prisma.OrientationTypeOrderByWithRelationInput | Prisma.OrientationTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrientationTypes.
   */
  cursor?: Prisma.OrientationTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrientationTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrientationTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrientationTypes.
   */
  distinct?: Prisma.OrientationTypeScalarFieldEnum | Prisma.OrientationTypeScalarFieldEnum[]
}

/**
 * OrientationType findFirstOrThrow
 */
export type OrientationTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter, which OrientationType to fetch.
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrientationTypes to fetch.
   */
  orderBy?: Prisma.OrientationTypeOrderByWithRelationInput | Prisma.OrientationTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrientationTypes.
   */
  cursor?: Prisma.OrientationTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrientationTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrientationTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrientationTypes.
   */
  distinct?: Prisma.OrientationTypeScalarFieldEnum | Prisma.OrientationTypeScalarFieldEnum[]
}

/**
 * OrientationType findMany
 */
export type OrientationTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter, which OrientationTypes to fetch.
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrientationTypes to fetch.
   */
  orderBy?: Prisma.OrientationTypeOrderByWithRelationInput | Prisma.OrientationTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrientationTypes.
   */
  cursor?: Prisma.OrientationTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrientationTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrientationTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrientationTypes.
   */
  distinct?: Prisma.OrientationTypeScalarFieldEnum | Prisma.OrientationTypeScalarFieldEnum[]
}

/**
 * OrientationType create
 */
export type OrientationTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a OrientationType.
   */
  data: Prisma.XOR<Prisma.OrientationTypeCreateInput, Prisma.OrientationTypeUncheckedCreateInput>
}

/**
 * OrientationType createMany
 */
export type OrientationTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrientationTypes.
   */
  data: Prisma.OrientationTypeCreateManyInput | Prisma.OrientationTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrientationType createManyAndReturn
 */
export type OrientationTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * The data used to create many OrientationTypes.
   */
  data: Prisma.OrientationTypeCreateManyInput | Prisma.OrientationTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrientationType update
 */
export type OrientationTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a OrientationType.
   */
  data: Prisma.XOR<Prisma.OrientationTypeUpdateInput, Prisma.OrientationTypeUncheckedUpdateInput>
  /**
   * Choose, which OrientationType to update.
   */
  where: Prisma.OrientationTypeWhereUniqueInput
}

/**
 * OrientationType updateMany
 */
export type OrientationTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrientationTypes.
   */
  data: Prisma.XOR<Prisma.OrientationTypeUpdateManyMutationInput, Prisma.OrientationTypeUncheckedUpdateManyInput>
  /**
   * Filter which OrientationTypes to update
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * Limit how many OrientationTypes to update.
   */
  limit?: number
}

/**
 * OrientationType updateManyAndReturn
 */
export type OrientationTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * The data used to update OrientationTypes.
   */
  data: Prisma.XOR<Prisma.OrientationTypeUpdateManyMutationInput, Prisma.OrientationTypeUncheckedUpdateManyInput>
  /**
   * Filter which OrientationTypes to update
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * Limit how many OrientationTypes to update.
   */
  limit?: number
}

/**
 * OrientationType upsert
 */
export type OrientationTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the OrientationType to update in case it exists.
   */
  where: Prisma.OrientationTypeWhereUniqueInput
  /**
   * In case the OrientationType found by the `where` argument doesn't exist, create a new OrientationType with this data.
   */
  create: Prisma.XOR<Prisma.OrientationTypeCreateInput, Prisma.OrientationTypeUncheckedCreateInput>
  /**
   * In case the OrientationType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrientationTypeUpdateInput, Prisma.OrientationTypeUncheckedUpdateInput>
}

/**
 * OrientationType delete
 */
export type OrientationTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
  /**
   * Filter which OrientationType to delete.
   */
  where: Prisma.OrientationTypeWhereUniqueInput
}

/**
 * OrientationType deleteMany
 */
export type OrientationTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrientationTypes to delete
   */
  where?: Prisma.OrientationTypeWhereInput
  /**
   * Limit how many OrientationTypes to delete.
   */
  limit?: number
}

/**
 * OrientationType.mentors
 */
export type OrientationType$mentorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MentorOrientationType
   */
  select?: Prisma.MentorOrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MentorOrientationType
   */
  omit?: Prisma.MentorOrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MentorOrientationTypeInclude<ExtArgs> | null
  where?: Prisma.MentorOrientationTypeWhereInput
  orderBy?: Prisma.MentorOrientationTypeOrderByWithRelationInput | Prisma.MentorOrientationTypeOrderByWithRelationInput[]
  cursor?: Prisma.MentorOrientationTypeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MentorOrientationTypeScalarFieldEnum | Prisma.MentorOrientationTypeScalarFieldEnum[]
}

/**
 * OrientationType.appointments
 */
export type OrientationType$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * OrientationType without action
 */
export type OrientationTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrientationType
   */
  select?: Prisma.OrientationTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrientationType
   */
  omit?: Prisma.OrientationTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrientationTypeInclude<ExtArgs> | null
}
