
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RegistrationStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RegistrationStatus
 * 
 */
export type RegistrationStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$RegistrationStatusPayload>

export type AggregateRegistrationStatus = {
  _count: RegistrationStatusCountAggregateOutputType | null
  _min: RegistrationStatusMinAggregateOutputType | null
  _max: RegistrationStatusMaxAggregateOutputType | null
}

export type RegistrationStatusMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RegistrationStatusMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RegistrationStatusCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RegistrationStatusMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type RegistrationStatusMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type RegistrationStatusCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RegistrationStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RegistrationStatus to aggregate.
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegistrationStatuses to fetch.
   */
  orderBy?: Prisma.RegistrationStatusOrderByWithRelationInput | Prisma.RegistrationStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RegistrationStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegistrationStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegistrationStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RegistrationStatuses
  **/
  _count?: true | RegistrationStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegistrationStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegistrationStatusMaxAggregateInputType
}

export type GetRegistrationStatusAggregateType<T extends RegistrationStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateRegistrationStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegistrationStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateRegistrationStatus[P]>
}




export type RegistrationStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegistrationStatusWhereInput
  orderBy?: Prisma.RegistrationStatusOrderByWithAggregationInput | Prisma.RegistrationStatusOrderByWithAggregationInput[]
  by: Prisma.RegistrationStatusScalarFieldEnum[] | Prisma.RegistrationStatusScalarFieldEnum
  having?: Prisma.RegistrationStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegistrationStatusCountAggregateInputType | true
  _min?: RegistrationStatusMinAggregateInputType
  _max?: RegistrationStatusMaxAggregateInputType
}

export type RegistrationStatusGroupByOutputType = {
  id: string
  title: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: RegistrationStatusCountAggregateOutputType | null
  _min: RegistrationStatusMinAggregateOutputType | null
  _max: RegistrationStatusMaxAggregateOutputType | null
}

export type GetRegistrationStatusGroupByPayload<T extends RegistrationStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegistrationStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegistrationStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegistrationStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegistrationStatusGroupByOutputType[P]>
      }
    >
  >



export type RegistrationStatusWhereInput = {
  AND?: Prisma.RegistrationStatusWhereInput | Prisma.RegistrationStatusWhereInput[]
  OR?: Prisma.RegistrationStatusWhereInput[]
  NOT?: Prisma.RegistrationStatusWhereInput | Prisma.RegistrationStatusWhereInput[]
  id?: Prisma.UuidFilter<"RegistrationStatus"> | string
  title?: Prisma.StringFilter<"RegistrationStatus"> | string
  description?: Prisma.StringNullableFilter<"RegistrationStatus"> | string | null
  createdAt?: Prisma.DateTimeFilter<"RegistrationStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RegistrationStatus"> | Date | string
  eventRegistrations?: Prisma.EventRegistrationListRelationFilter
}

export type RegistrationStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  eventRegistrations?: Prisma.EventRegistrationOrderByRelationAggregateInput
}

export type RegistrationStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.RegistrationStatusWhereInput | Prisma.RegistrationStatusWhereInput[]
  OR?: Prisma.RegistrationStatusWhereInput[]
  NOT?: Prisma.RegistrationStatusWhereInput | Prisma.RegistrationStatusWhereInput[]
  description?: Prisma.StringNullableFilter<"RegistrationStatus"> | string | null
  createdAt?: Prisma.DateTimeFilter<"RegistrationStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RegistrationStatus"> | Date | string
  eventRegistrations?: Prisma.EventRegistrationListRelationFilter
}, "id" | "title">

export type RegistrationStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RegistrationStatusCountOrderByAggregateInput
  _max?: Prisma.RegistrationStatusMaxOrderByAggregateInput
  _min?: Prisma.RegistrationStatusMinOrderByAggregateInput
}

export type RegistrationStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.RegistrationStatusScalarWhereWithAggregatesInput | Prisma.RegistrationStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.RegistrationStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RegistrationStatusScalarWhereWithAggregatesInput | Prisma.RegistrationStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"RegistrationStatus"> | string
  title?: Prisma.StringWithAggregatesFilter<"RegistrationStatus"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"RegistrationStatus"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RegistrationStatus"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RegistrationStatus"> | Date | string
}

export type RegistrationStatusCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  eventRegistrations?: Prisma.EventRegistrationCreateNestedManyWithoutStatusInput
}

export type RegistrationStatusUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  eventRegistrations?: Prisma.EventRegistrationUncheckedCreateNestedManyWithoutStatusInput
}

export type RegistrationStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventRegistrations?: Prisma.EventRegistrationUpdateManyWithoutStatusNestedInput
}

export type RegistrationStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventRegistrations?: Prisma.EventRegistrationUncheckedUpdateManyWithoutStatusNestedInput
}

export type RegistrationStatusCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationStatusScalarRelationFilter = {
  is?: Prisma.RegistrationStatusWhereInput
  isNot?: Prisma.RegistrationStatusWhereInput
}

export type RegistrationStatusCreateNestedOneWithoutEventRegistrationsInput = {
  create?: Prisma.XOR<Prisma.RegistrationStatusCreateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedCreateWithoutEventRegistrationsInput>
  connectOrCreate?: Prisma.RegistrationStatusCreateOrConnectWithoutEventRegistrationsInput
  connect?: Prisma.RegistrationStatusWhereUniqueInput
}

export type RegistrationStatusUpdateOneRequiredWithoutEventRegistrationsNestedInput = {
  create?: Prisma.XOR<Prisma.RegistrationStatusCreateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedCreateWithoutEventRegistrationsInput>
  connectOrCreate?: Prisma.RegistrationStatusCreateOrConnectWithoutEventRegistrationsInput
  upsert?: Prisma.RegistrationStatusUpsertWithoutEventRegistrationsInput
  connect?: Prisma.RegistrationStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RegistrationStatusUpdateToOneWithWhereWithoutEventRegistrationsInput, Prisma.RegistrationStatusUpdateWithoutEventRegistrationsInput>, Prisma.RegistrationStatusUncheckedUpdateWithoutEventRegistrationsInput>
}

export type RegistrationStatusCreateWithoutEventRegistrationsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationStatusUncheckedCreateWithoutEventRegistrationsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationStatusCreateOrConnectWithoutEventRegistrationsInput = {
  where: Prisma.RegistrationStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.RegistrationStatusCreateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedCreateWithoutEventRegistrationsInput>
}

export type RegistrationStatusUpsertWithoutEventRegistrationsInput = {
  update: Prisma.XOR<Prisma.RegistrationStatusUpdateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedUpdateWithoutEventRegistrationsInput>
  create: Prisma.XOR<Prisma.RegistrationStatusCreateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedCreateWithoutEventRegistrationsInput>
  where?: Prisma.RegistrationStatusWhereInput
}

export type RegistrationStatusUpdateToOneWithWhereWithoutEventRegistrationsInput = {
  where?: Prisma.RegistrationStatusWhereInput
  data: Prisma.XOR<Prisma.RegistrationStatusUpdateWithoutEventRegistrationsInput, Prisma.RegistrationStatusUncheckedUpdateWithoutEventRegistrationsInput>
}

export type RegistrationStatusUpdateWithoutEventRegistrationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationStatusUncheckedUpdateWithoutEventRegistrationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type RegistrationStatusCountOutputType
 */

export type RegistrationStatusCountOutputType = {
  eventRegistrations: number
}

export type RegistrationStatusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventRegistrations?: boolean | RegistrationStatusCountOutputTypeCountEventRegistrationsArgs
}

/**
 * RegistrationStatusCountOutputType without action
 */
export type RegistrationStatusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatusCountOutputType
   */
  select?: Prisma.RegistrationStatusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RegistrationStatusCountOutputType without action
 */
export type RegistrationStatusCountOutputTypeCountEventRegistrationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventRegistrationWhereInput
}


export type RegistrationStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  eventRegistrations?: boolean | Prisma.RegistrationStatus$eventRegistrationsArgs<ExtArgs>
  _count?: boolean | Prisma.RegistrationStatusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["registrationStatus"]>

export type RegistrationStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["registrationStatus"]>

export type RegistrationStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["registrationStatus"]>

export type RegistrationStatusSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RegistrationStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["registrationStatus"]>
export type RegistrationStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventRegistrations?: boolean | Prisma.RegistrationStatus$eventRegistrationsArgs<ExtArgs>
  _count?: boolean | Prisma.RegistrationStatusCountOutputTypeDefaultArgs<ExtArgs>
}
export type RegistrationStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RegistrationStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RegistrationStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RegistrationStatus"
  objects: {
    eventRegistrations: Prisma.$EventRegistrationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["registrationStatus"]>
  composites: {}
}

export type RegistrationStatusGetPayload<S extends boolean | null | undefined | RegistrationStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload, S>

export type RegistrationStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RegistrationStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegistrationStatusCountAggregateInputType | true
  }

export interface RegistrationStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RegistrationStatus'], meta: { name: 'RegistrationStatus' } }
  /**
   * Find zero or one RegistrationStatus that matches the filter.
   * @param {RegistrationStatusFindUniqueArgs} args - Arguments to find a RegistrationStatus
   * @example
   * // Get one RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RegistrationStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, RegistrationStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RegistrationStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RegistrationStatusFindUniqueOrThrowArgs} args - Arguments to find a RegistrationStatus
   * @example
   * // Get one RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RegistrationStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RegistrationStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RegistrationStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusFindFirstArgs} args - Arguments to find a RegistrationStatus
   * @example
   * // Get one RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RegistrationStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RegistrationStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusFindFirstOrThrowArgs} args - Arguments to find a RegistrationStatus
   * @example
   * // Get one RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RegistrationStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RegistrationStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RegistrationStatuses
   * const registrationStatuses = await prisma.registrationStatus.findMany()
   * 
   * // Get first 10 RegistrationStatuses
   * const registrationStatuses = await prisma.registrationStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const registrationStatusWithIdOnly = await prisma.registrationStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RegistrationStatusFindManyArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RegistrationStatus.
   * @param {RegistrationStatusCreateArgs} args - Arguments to create a RegistrationStatus.
   * @example
   * // Create one RegistrationStatus
   * const RegistrationStatus = await prisma.registrationStatus.create({
   *   data: {
   *     // ... data to create a RegistrationStatus
   *   }
   * })
   * 
   */
  create<T extends RegistrationStatusCreateArgs>(args: Prisma.SelectSubset<T, RegistrationStatusCreateArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RegistrationStatuses.
   * @param {RegistrationStatusCreateManyArgs} args - Arguments to create many RegistrationStatuses.
   * @example
   * // Create many RegistrationStatuses
   * const registrationStatus = await prisma.registrationStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RegistrationStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RegistrationStatuses and returns the data saved in the database.
   * @param {RegistrationStatusCreateManyAndReturnArgs} args - Arguments to create many RegistrationStatuses.
   * @example
   * // Create many RegistrationStatuses
   * const registrationStatus = await prisma.registrationStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RegistrationStatuses and only return the `id`
   * const registrationStatusWithIdOnly = await prisma.registrationStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RegistrationStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RegistrationStatus.
   * @param {RegistrationStatusDeleteArgs} args - Arguments to delete one RegistrationStatus.
   * @example
   * // Delete one RegistrationStatus
   * const RegistrationStatus = await prisma.registrationStatus.delete({
   *   where: {
   *     // ... filter to delete one RegistrationStatus
   *   }
   * })
   * 
   */
  delete<T extends RegistrationStatusDeleteArgs>(args: Prisma.SelectSubset<T, RegistrationStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RegistrationStatus.
   * @param {RegistrationStatusUpdateArgs} args - Arguments to update one RegistrationStatus.
   * @example
   * // Update one RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RegistrationStatusUpdateArgs>(args: Prisma.SelectSubset<T, RegistrationStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RegistrationStatuses.
   * @param {RegistrationStatusDeleteManyArgs} args - Arguments to filter RegistrationStatuses to delete.
   * @example
   * // Delete a few RegistrationStatuses
   * const { count } = await prisma.registrationStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RegistrationStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, RegistrationStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegistrationStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RegistrationStatuses
   * const registrationStatus = await prisma.registrationStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RegistrationStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, RegistrationStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegistrationStatuses and returns the data updated in the database.
   * @param {RegistrationStatusUpdateManyAndReturnArgs} args - Arguments to update many RegistrationStatuses.
   * @example
   * // Update many RegistrationStatuses
   * const registrationStatus = await prisma.registrationStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RegistrationStatuses and only return the `id`
   * const registrationStatusWithIdOnly = await prisma.registrationStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RegistrationStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RegistrationStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RegistrationStatus.
   * @param {RegistrationStatusUpsertArgs} args - Arguments to update or create a RegistrationStatus.
   * @example
   * // Update or create a RegistrationStatus
   * const registrationStatus = await prisma.registrationStatus.upsert({
   *   create: {
   *     // ... data to create a RegistrationStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RegistrationStatus we want to update
   *   }
   * })
   */
  upsert<T extends RegistrationStatusUpsertArgs>(args: Prisma.SelectSubset<T, RegistrationStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__RegistrationStatusClient<runtime.Types.Result.GetResult<Prisma.$RegistrationStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RegistrationStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusCountArgs} args - Arguments to filter RegistrationStatuses to count.
   * @example
   * // Count the number of RegistrationStatuses
   * const count = await prisma.registrationStatus.count({
   *   where: {
   *     // ... the filter for the RegistrationStatuses we want to count
   *   }
   * })
  **/
  count<T extends RegistrationStatusCountArgs>(
    args?: Prisma.Subset<T, RegistrationStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegistrationStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RegistrationStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegistrationStatusAggregateArgs>(args: Prisma.Subset<T, RegistrationStatusAggregateArgs>): Prisma.PrismaPromise<GetRegistrationStatusAggregateType<T>>

  /**
   * Group by RegistrationStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RegistrationStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RegistrationStatusGroupByArgs['orderBy'] }
      : { orderBy?: RegistrationStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RegistrationStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegistrationStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RegistrationStatus model
 */
readonly fields: RegistrationStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RegistrationStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RegistrationStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  eventRegistrations<T extends Prisma.RegistrationStatus$eventRegistrationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RegistrationStatus$eventRegistrationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventRegistrationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RegistrationStatus model
 */
export interface RegistrationStatusFieldRefs {
  readonly id: Prisma.FieldRef<"RegistrationStatus", 'String'>
  readonly title: Prisma.FieldRef<"RegistrationStatus", 'String'>
  readonly description: Prisma.FieldRef<"RegistrationStatus", 'String'>
  readonly createdAt: Prisma.FieldRef<"RegistrationStatus", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RegistrationStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RegistrationStatus findUnique
 */
export type RegistrationStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationStatus to fetch.
   */
  where: Prisma.RegistrationStatusWhereUniqueInput
}

/**
 * RegistrationStatus findUniqueOrThrow
 */
export type RegistrationStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationStatus to fetch.
   */
  where: Prisma.RegistrationStatusWhereUniqueInput
}

/**
 * RegistrationStatus findFirst
 */
export type RegistrationStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationStatus to fetch.
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegistrationStatuses to fetch.
   */
  orderBy?: Prisma.RegistrationStatusOrderByWithRelationInput | Prisma.RegistrationStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RegistrationStatuses.
   */
  cursor?: Prisma.RegistrationStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegistrationStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegistrationStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RegistrationStatuses.
   */
  distinct?: Prisma.RegistrationStatusScalarFieldEnum | Prisma.RegistrationStatusScalarFieldEnum[]
}

/**
 * RegistrationStatus findFirstOrThrow
 */
export type RegistrationStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationStatus to fetch.
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegistrationStatuses to fetch.
   */
  orderBy?: Prisma.RegistrationStatusOrderByWithRelationInput | Prisma.RegistrationStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RegistrationStatuses.
   */
  cursor?: Prisma.RegistrationStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegistrationStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegistrationStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RegistrationStatuses.
   */
  distinct?: Prisma.RegistrationStatusScalarFieldEnum | Prisma.RegistrationStatusScalarFieldEnum[]
}

/**
 * RegistrationStatus findMany
 */
export type RegistrationStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationStatuses to fetch.
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegistrationStatuses to fetch.
   */
  orderBy?: Prisma.RegistrationStatusOrderByWithRelationInput | Prisma.RegistrationStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RegistrationStatuses.
   */
  cursor?: Prisma.RegistrationStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegistrationStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegistrationStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RegistrationStatuses.
   */
  distinct?: Prisma.RegistrationStatusScalarFieldEnum | Prisma.RegistrationStatusScalarFieldEnum[]
}

/**
 * RegistrationStatus create
 */
export type RegistrationStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a RegistrationStatus.
   */
  data: Prisma.XOR<Prisma.RegistrationStatusCreateInput, Prisma.RegistrationStatusUncheckedCreateInput>
}

/**
 * RegistrationStatus createMany
 */
export type RegistrationStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RegistrationStatuses.
   */
  data: Prisma.RegistrationStatusCreateManyInput | Prisma.RegistrationStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RegistrationStatus createManyAndReturn
 */
export type RegistrationStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * The data used to create many RegistrationStatuses.
   */
  data: Prisma.RegistrationStatusCreateManyInput | Prisma.RegistrationStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RegistrationStatus update
 */
export type RegistrationStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a RegistrationStatus.
   */
  data: Prisma.XOR<Prisma.RegistrationStatusUpdateInput, Prisma.RegistrationStatusUncheckedUpdateInput>
  /**
   * Choose, which RegistrationStatus to update.
   */
  where: Prisma.RegistrationStatusWhereUniqueInput
}

/**
 * RegistrationStatus updateMany
 */
export type RegistrationStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RegistrationStatuses.
   */
  data: Prisma.XOR<Prisma.RegistrationStatusUpdateManyMutationInput, Prisma.RegistrationStatusUncheckedUpdateManyInput>
  /**
   * Filter which RegistrationStatuses to update
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * Limit how many RegistrationStatuses to update.
   */
  limit?: number
}

/**
 * RegistrationStatus updateManyAndReturn
 */
export type RegistrationStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * The data used to update RegistrationStatuses.
   */
  data: Prisma.XOR<Prisma.RegistrationStatusUpdateManyMutationInput, Prisma.RegistrationStatusUncheckedUpdateManyInput>
  /**
   * Filter which RegistrationStatuses to update
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * Limit how many RegistrationStatuses to update.
   */
  limit?: number
}

/**
 * RegistrationStatus upsert
 */
export type RegistrationStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the RegistrationStatus to update in case it exists.
   */
  where: Prisma.RegistrationStatusWhereUniqueInput
  /**
   * In case the RegistrationStatus found by the `where` argument doesn't exist, create a new RegistrationStatus with this data.
   */
  create: Prisma.XOR<Prisma.RegistrationStatusCreateInput, Prisma.RegistrationStatusUncheckedCreateInput>
  /**
   * In case the RegistrationStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RegistrationStatusUpdateInput, Prisma.RegistrationStatusUncheckedUpdateInput>
}

/**
 * RegistrationStatus delete
 */
export type RegistrationStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
  /**
   * Filter which RegistrationStatus to delete.
   */
  where: Prisma.RegistrationStatusWhereUniqueInput
}

/**
 * RegistrationStatus deleteMany
 */
export type RegistrationStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RegistrationStatuses to delete
   */
  where?: Prisma.RegistrationStatusWhereInput
  /**
   * Limit how many RegistrationStatuses to delete.
   */
  limit?: number
}

/**
 * RegistrationStatus.eventRegistrations
 */
export type RegistrationStatus$eventRegistrationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventRegistration
   */
  select?: Prisma.EventRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventRegistration
   */
  omit?: Prisma.EventRegistrationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventRegistrationInclude<ExtArgs> | null
  where?: Prisma.EventRegistrationWhereInput
  orderBy?: Prisma.EventRegistrationOrderByWithRelationInput | Prisma.EventRegistrationOrderByWithRelationInput[]
  cursor?: Prisma.EventRegistrationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventRegistrationScalarFieldEnum | Prisma.EventRegistrationScalarFieldEnum[]
}

/**
 * RegistrationStatus without action
 */
export type RegistrationStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistrationStatus
   */
  select?: Prisma.RegistrationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationStatus
   */
  omit?: Prisma.RegistrationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationStatusInclude<ExtArgs> | null
}
