
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TimeProposal` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TimeProposal
 * 
 */
export type TimeProposalModel = runtime.Types.Result.DefaultSelection<Prisma.$TimeProposalPayload>

export type AggregateTimeProposal = {
  _count: TimeProposalCountAggregateOutputType | null
  _min: TimeProposalMinAggregateOutputType | null
  _max: TimeProposalMaxAggregateOutputType | null
}

export type TimeProposalMinAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  proposedBlockId: string | null
  message: string | null
  statusId: string | null
  createdAt: Date | null
  respondedAt: Date | null
  updatedAt: Date | null
}

export type TimeProposalMaxAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  proposedBlockId: string | null
  message: string | null
  statusId: string | null
  createdAt: Date | null
  respondedAt: Date | null
  updatedAt: Date | null
}

export type TimeProposalCountAggregateOutputType = {
  id: number
  appointmentId: number
  proposedBlockId: number
  message: number
  statusId: number
  createdAt: number
  respondedAt: number
  updatedAt: number
  _all: number
}


export type TimeProposalMinAggregateInputType = {
  id?: true
  appointmentId?: true
  proposedBlockId?: true
  message?: true
  statusId?: true
  createdAt?: true
  respondedAt?: true
  updatedAt?: true
}

export type TimeProposalMaxAggregateInputType = {
  id?: true
  appointmentId?: true
  proposedBlockId?: true
  message?: true
  statusId?: true
  createdAt?: true
  respondedAt?: true
  updatedAt?: true
}

export type TimeProposalCountAggregateInputType = {
  id?: true
  appointmentId?: true
  proposedBlockId?: true
  message?: true
  statusId?: true
  createdAt?: true
  respondedAt?: true
  updatedAt?: true
  _all?: true
}

export type TimeProposalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeProposal to aggregate.
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeProposals to fetch.
   */
  orderBy?: Prisma.TimeProposalOrderByWithRelationInput | Prisma.TimeProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimeProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeProposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeProposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TimeProposals
  **/
  _count?: true | TimeProposalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeProposalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeProposalMaxAggregateInputType
}

export type GetTimeProposalAggregateType<T extends TimeProposalAggregateArgs> = {
      [P in keyof T & keyof AggregateTimeProposal]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTimeProposal[P]>
    : Prisma.GetScalarType<T[P], AggregateTimeProposal[P]>
}




export type TimeProposalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeProposalWhereInput
  orderBy?: Prisma.TimeProposalOrderByWithAggregationInput | Prisma.TimeProposalOrderByWithAggregationInput[]
  by: Prisma.TimeProposalScalarFieldEnum[] | Prisma.TimeProposalScalarFieldEnum
  having?: Prisma.TimeProposalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeProposalCountAggregateInputType | true
  _min?: TimeProposalMinAggregateInputType
  _max?: TimeProposalMaxAggregateInputType
}

export type TimeProposalGroupByOutputType = {
  id: string
  appointmentId: string
  proposedBlockId: string
  message: string | null
  statusId: string
  createdAt: Date
  respondedAt: Date | null
  updatedAt: Date
  _count: TimeProposalCountAggregateOutputType | null
  _min: TimeProposalMinAggregateOutputType | null
  _max: TimeProposalMaxAggregateOutputType | null
}

export type GetTimeProposalGroupByPayload<T extends TimeProposalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeProposalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeProposalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeProposalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeProposalGroupByOutputType[P]>
      }
    >
  >



export type TimeProposalWhereInput = {
  AND?: Prisma.TimeProposalWhereInput | Prisma.TimeProposalWhereInput[]
  OR?: Prisma.TimeProposalWhereInput[]
  NOT?: Prisma.TimeProposalWhereInput | Prisma.TimeProposalWhereInput[]
  id?: Prisma.UuidFilter<"TimeProposal"> | string
  appointmentId?: Prisma.UuidFilter<"TimeProposal"> | string
  proposedBlockId?: Prisma.UuidFilter<"TimeProposal"> | string
  message?: Prisma.StringNullableFilter<"TimeProposal"> | string | null
  statusId?: Prisma.UuidFilter<"TimeProposal"> | string
  createdAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
  respondedAt?: Prisma.DateTimeNullableFilter<"TimeProposal"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  proposedBlock?: Prisma.XOR<Prisma.AvailabilityBlockScalarRelationFilter, Prisma.AvailabilityBlockWhereInput>
  status?: Prisma.XOR<Prisma.ProposalStatusScalarRelationFilter, Prisma.ProposalStatusWhereInput>
}

export type TimeProposalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  proposedBlockId?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  statusId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  respondedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  appointment?: Prisma.AppointmentOrderByWithRelationInput
  proposedBlock?: Prisma.AvailabilityBlockOrderByWithRelationInput
  status?: Prisma.ProposalStatusOrderByWithRelationInput
}

export type TimeProposalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TimeProposalWhereInput | Prisma.TimeProposalWhereInput[]
  OR?: Prisma.TimeProposalWhereInput[]
  NOT?: Prisma.TimeProposalWhereInput | Prisma.TimeProposalWhereInput[]
  appointmentId?: Prisma.UuidFilter<"TimeProposal"> | string
  proposedBlockId?: Prisma.UuidFilter<"TimeProposal"> | string
  message?: Prisma.StringNullableFilter<"TimeProposal"> | string | null
  statusId?: Prisma.UuidFilter<"TimeProposal"> | string
  createdAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
  respondedAt?: Prisma.DateTimeNullableFilter<"TimeProposal"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  proposedBlock?: Prisma.XOR<Prisma.AvailabilityBlockScalarRelationFilter, Prisma.AvailabilityBlockWhereInput>
  status?: Prisma.XOR<Prisma.ProposalStatusScalarRelationFilter, Prisma.ProposalStatusWhereInput>
}, "id">

export type TimeProposalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  proposedBlockId?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  statusId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  respondedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TimeProposalCountOrderByAggregateInput
  _max?: Prisma.TimeProposalMaxOrderByAggregateInput
  _min?: Prisma.TimeProposalMinOrderByAggregateInput
}

export type TimeProposalScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimeProposalScalarWhereWithAggregatesInput | Prisma.TimeProposalScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimeProposalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimeProposalScalarWhereWithAggregatesInput | Prisma.TimeProposalScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"TimeProposal"> | string
  appointmentId?: Prisma.UuidWithAggregatesFilter<"TimeProposal"> | string
  proposedBlockId?: Prisma.UuidWithAggregatesFilter<"TimeProposal"> | string
  message?: Prisma.StringNullableWithAggregatesFilter<"TimeProposal"> | string | null
  statusId?: Prisma.UuidWithAggregatesFilter<"TimeProposal"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TimeProposal"> | Date | string
  respondedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TimeProposal"> | Date | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TimeProposal"> | Date | string
}

export type TimeProposalCreateInput = {
  id?: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
  appointment: Prisma.AppointmentCreateNestedOneWithoutProposalsInput
  proposedBlock: Prisma.AvailabilityBlockCreateNestedOneWithoutProposalsInput
  status: Prisma.ProposalStatusCreateNestedOneWithoutProposalsInput
}

export type TimeProposalUncheckedCreateInput = {
  id?: string
  appointmentId: string
  proposedBlockId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutProposalsNestedInput
  proposedBlock?: Prisma.AvailabilityBlockUpdateOneRequiredWithoutProposalsNestedInput
  status?: Prisma.ProposalStatusUpdateOneRequiredWithoutProposalsNestedInput
}

export type TimeProposalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalCreateManyInput = {
  id?: string
  appointmentId: string
  proposedBlockId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalListRelationFilter = {
  every?: Prisma.TimeProposalWhereInput
  some?: Prisma.TimeProposalWhereInput
  none?: Prisma.TimeProposalWhereInput
}

export type TimeProposalOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimeProposalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  proposedBlockId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  respondedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeProposalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  proposedBlockId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  respondedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeProposalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  proposedBlockId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  respondedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeProposalCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput> | Prisma.TimeProposalCreateWithoutStatusInput[] | Prisma.TimeProposalUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutStatusInput | Prisma.TimeProposalCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.TimeProposalCreateManyStatusInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUncheckedCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput> | Prisma.TimeProposalCreateWithoutStatusInput[] | Prisma.TimeProposalUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutStatusInput | Prisma.TimeProposalCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.TimeProposalCreateManyStatusInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput> | Prisma.TimeProposalCreateWithoutStatusInput[] | Prisma.TimeProposalUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutStatusInput | Prisma.TimeProposalCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutStatusInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.TimeProposalCreateManyStatusInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutStatusInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutStatusInput | Prisma.TimeProposalUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalUncheckedUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput> | Prisma.TimeProposalCreateWithoutStatusInput[] | Prisma.TimeProposalUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutStatusInput | Prisma.TimeProposalCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutStatusInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.TimeProposalCreateManyStatusInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutStatusInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutStatusInput | Prisma.TimeProposalUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalCreateNestedManyWithoutProposedBlockInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput> | Prisma.TimeProposalCreateWithoutProposedBlockInput[] | Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput | Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput[]
  createMany?: Prisma.TimeProposalCreateManyProposedBlockInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUncheckedCreateNestedManyWithoutProposedBlockInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput> | Prisma.TimeProposalCreateWithoutProposedBlockInput[] | Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput | Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput[]
  createMany?: Prisma.TimeProposalCreateManyProposedBlockInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUpdateManyWithoutProposedBlockNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput> | Prisma.TimeProposalCreateWithoutProposedBlockInput[] | Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput | Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutProposedBlockInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutProposedBlockInput[]
  createMany?: Prisma.TimeProposalCreateManyProposedBlockInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutProposedBlockInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutProposedBlockInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutProposedBlockInput | Prisma.TimeProposalUpdateManyWithWhereWithoutProposedBlockInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalUncheckedUpdateManyWithoutProposedBlockNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput> | Prisma.TimeProposalCreateWithoutProposedBlockInput[] | Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput | Prisma.TimeProposalCreateOrConnectWithoutProposedBlockInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutProposedBlockInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutProposedBlockInput[]
  createMany?: Prisma.TimeProposalCreateManyProposedBlockInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutProposedBlockInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutProposedBlockInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutProposedBlockInput | Prisma.TimeProposalUpdateManyWithWhereWithoutProposedBlockInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput> | Prisma.TimeProposalCreateWithoutAppointmentInput[] | Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput | Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.TimeProposalCreateManyAppointmentInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUncheckedCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput> | Prisma.TimeProposalCreateWithoutAppointmentInput[] | Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput | Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.TimeProposalCreateManyAppointmentInputEnvelope
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
}

export type TimeProposalUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput> | Prisma.TimeProposalCreateWithoutAppointmentInput[] | Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput | Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.TimeProposalCreateManyAppointmentInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutAppointmentInput | Prisma.TimeProposalUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalUncheckedUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput> | Prisma.TimeProposalCreateWithoutAppointmentInput[] | Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput | Prisma.TimeProposalCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.TimeProposalUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.TimeProposalUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.TimeProposalCreateManyAppointmentInputEnvelope
  set?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  disconnect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  delete?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  connect?: Prisma.TimeProposalWhereUniqueInput | Prisma.TimeProposalWhereUniqueInput[]
  update?: Prisma.TimeProposalUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.TimeProposalUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.TimeProposalUpdateManyWithWhereWithoutAppointmentInput | Prisma.TimeProposalUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
}

export type TimeProposalCreateWithoutStatusInput = {
  id?: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
  appointment: Prisma.AppointmentCreateNestedOneWithoutProposalsInput
  proposedBlock: Prisma.AvailabilityBlockCreateNestedOneWithoutProposalsInput
}

export type TimeProposalUncheckedCreateWithoutStatusInput = {
  id?: string
  appointmentId: string
  proposedBlockId: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalCreateOrConnectWithoutStatusInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput>
}

export type TimeProposalCreateManyStatusInputEnvelope = {
  data: Prisma.TimeProposalCreateManyStatusInput | Prisma.TimeProposalCreateManyStatusInput[]
  skipDuplicates?: boolean
}

export type TimeProposalUpsertWithWhereUniqueWithoutStatusInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeProposalUpdateWithoutStatusInput, Prisma.TimeProposalUncheckedUpdateWithoutStatusInput>
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutStatusInput, Prisma.TimeProposalUncheckedCreateWithoutStatusInput>
}

export type TimeProposalUpdateWithWhereUniqueWithoutStatusInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateWithoutStatusInput, Prisma.TimeProposalUncheckedUpdateWithoutStatusInput>
}

export type TimeProposalUpdateManyWithWhereWithoutStatusInput = {
  where: Prisma.TimeProposalScalarWhereInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateManyMutationInput, Prisma.TimeProposalUncheckedUpdateManyWithoutStatusInput>
}

export type TimeProposalScalarWhereInput = {
  AND?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
  OR?: Prisma.TimeProposalScalarWhereInput[]
  NOT?: Prisma.TimeProposalScalarWhereInput | Prisma.TimeProposalScalarWhereInput[]
  id?: Prisma.UuidFilter<"TimeProposal"> | string
  appointmentId?: Prisma.UuidFilter<"TimeProposal"> | string
  proposedBlockId?: Prisma.UuidFilter<"TimeProposal"> | string
  message?: Prisma.StringNullableFilter<"TimeProposal"> | string | null
  statusId?: Prisma.UuidFilter<"TimeProposal"> | string
  createdAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
  respondedAt?: Prisma.DateTimeNullableFilter<"TimeProposal"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"TimeProposal"> | Date | string
}

export type TimeProposalCreateWithoutProposedBlockInput = {
  id?: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
  appointment: Prisma.AppointmentCreateNestedOneWithoutProposalsInput
  status: Prisma.ProposalStatusCreateNestedOneWithoutProposalsInput
}

export type TimeProposalUncheckedCreateWithoutProposedBlockInput = {
  id?: string
  appointmentId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalCreateOrConnectWithoutProposedBlockInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput>
}

export type TimeProposalCreateManyProposedBlockInputEnvelope = {
  data: Prisma.TimeProposalCreateManyProposedBlockInput | Prisma.TimeProposalCreateManyProposedBlockInput[]
  skipDuplicates?: boolean
}

export type TimeProposalUpsertWithWhereUniqueWithoutProposedBlockInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeProposalUpdateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedUpdateWithoutProposedBlockInput>
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedCreateWithoutProposedBlockInput>
}

export type TimeProposalUpdateWithWhereUniqueWithoutProposedBlockInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateWithoutProposedBlockInput, Prisma.TimeProposalUncheckedUpdateWithoutProposedBlockInput>
}

export type TimeProposalUpdateManyWithWhereWithoutProposedBlockInput = {
  where: Prisma.TimeProposalScalarWhereInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateManyMutationInput, Prisma.TimeProposalUncheckedUpdateManyWithoutProposedBlockInput>
}

export type TimeProposalCreateWithoutAppointmentInput = {
  id?: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
  proposedBlock: Prisma.AvailabilityBlockCreateNestedOneWithoutProposalsInput
  status: Prisma.ProposalStatusCreateNestedOneWithoutProposalsInput
}

export type TimeProposalUncheckedCreateWithoutAppointmentInput = {
  id?: string
  proposedBlockId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalCreateOrConnectWithoutAppointmentInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput>
}

export type TimeProposalCreateManyAppointmentInputEnvelope = {
  data: Prisma.TimeProposalCreateManyAppointmentInput | Prisma.TimeProposalCreateManyAppointmentInput[]
  skipDuplicates?: boolean
}

export type TimeProposalUpsertWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeProposalUpdateWithoutAppointmentInput, Prisma.TimeProposalUncheckedUpdateWithoutAppointmentInput>
  create: Prisma.XOR<Prisma.TimeProposalCreateWithoutAppointmentInput, Prisma.TimeProposalUncheckedCreateWithoutAppointmentInput>
}

export type TimeProposalUpdateWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.TimeProposalWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateWithoutAppointmentInput, Prisma.TimeProposalUncheckedUpdateWithoutAppointmentInput>
}

export type TimeProposalUpdateManyWithWhereWithoutAppointmentInput = {
  where: Prisma.TimeProposalScalarWhereInput
  data: Prisma.XOR<Prisma.TimeProposalUpdateManyMutationInput, Prisma.TimeProposalUncheckedUpdateManyWithoutAppointmentInput>
}

export type TimeProposalCreateManyStatusInput = {
  id?: string
  appointmentId: string
  proposedBlockId: string
  message?: string | null
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutProposalsNestedInput
  proposedBlock?: Prisma.AvailabilityBlockUpdateOneRequiredWithoutProposalsNestedInput
}

export type TimeProposalUncheckedUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalUncheckedUpdateManyWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalCreateManyProposedBlockInput = {
  id?: string
  appointmentId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalUpdateWithoutProposedBlockInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutProposalsNestedInput
  status?: Prisma.ProposalStatusUpdateOneRequiredWithoutProposalsNestedInput
}

export type TimeProposalUncheckedUpdateWithoutProposedBlockInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalUncheckedUpdateManyWithoutProposedBlockInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalCreateManyAppointmentInput = {
  id?: string
  proposedBlockId: string
  message?: string | null
  statusId: string
  createdAt?: Date | string
  respondedAt?: Date | string | null
  updatedAt?: Date | string
}

export type TimeProposalUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposedBlock?: Prisma.AvailabilityBlockUpdateOneRequiredWithoutProposalsNestedInput
  status?: Prisma.ProposalStatusUpdateOneRequiredWithoutProposalsNestedInput
}

export type TimeProposalUncheckedUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeProposalUncheckedUpdateManyWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proposedBlockId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  respondedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TimeProposalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  proposedBlockId?: boolean
  message?: boolean
  statusId?: boolean
  createdAt?: boolean
  respondedAt?: boolean
  updatedAt?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeProposal"]>

export type TimeProposalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  proposedBlockId?: boolean
  message?: boolean
  statusId?: boolean
  createdAt?: boolean
  respondedAt?: boolean
  updatedAt?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeProposal"]>

export type TimeProposalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  proposedBlockId?: boolean
  message?: boolean
  statusId?: boolean
  createdAt?: boolean
  respondedAt?: boolean
  updatedAt?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeProposal"]>

export type TimeProposalSelectScalar = {
  id?: boolean
  appointmentId?: boolean
  proposedBlockId?: boolean
  message?: boolean
  statusId?: boolean
  createdAt?: boolean
  respondedAt?: boolean
  updatedAt?: boolean
}

export type TimeProposalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "appointmentId" | "proposedBlockId" | "message" | "statusId" | "createdAt" | "respondedAt" | "updatedAt", ExtArgs["result"]["timeProposal"]>
export type TimeProposalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}
export type TimeProposalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}
export type TimeProposalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  proposedBlock?: boolean | Prisma.AvailabilityBlockDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ProposalStatusDefaultArgs<ExtArgs>
}

export type $TimeProposalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TimeProposal"
  objects: {
    appointment: Prisma.$AppointmentPayload<ExtArgs>
    proposedBlock: Prisma.$AvailabilityBlockPayload<ExtArgs>
    status: Prisma.$ProposalStatusPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    appointmentId: string
    proposedBlockId: string
    message: string | null
    statusId: string
    createdAt: Date
    respondedAt: Date | null
    updatedAt: Date
  }, ExtArgs["result"]["timeProposal"]>
  composites: {}
}

export type TimeProposalGetPayload<S extends boolean | null | undefined | TimeProposalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload, S>

export type TimeProposalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimeProposalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimeProposalCountAggregateInputType | true
  }

export interface TimeProposalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TimeProposal'], meta: { name: 'TimeProposal' } }
  /**
   * Find zero or one TimeProposal that matches the filter.
   * @param {TimeProposalFindUniqueArgs} args - Arguments to find a TimeProposal
   * @example
   * // Get one TimeProposal
   * const timeProposal = await prisma.timeProposal.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimeProposalFindUniqueArgs>(args: Prisma.SelectSubset<T, TimeProposalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TimeProposal that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimeProposalFindUniqueOrThrowArgs} args - Arguments to find a TimeProposal
   * @example
   * // Get one TimeProposal
   * const timeProposal = await prisma.timeProposal.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimeProposalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimeProposalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeProposal that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalFindFirstArgs} args - Arguments to find a TimeProposal
   * @example
   * // Get one TimeProposal
   * const timeProposal = await prisma.timeProposal.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimeProposalFindFirstArgs>(args?: Prisma.SelectSubset<T, TimeProposalFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeProposal that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalFindFirstOrThrowArgs} args - Arguments to find a TimeProposal
   * @example
   * // Get one TimeProposal
   * const timeProposal = await prisma.timeProposal.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimeProposalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimeProposalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TimeProposals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TimeProposals
   * const timeProposals = await prisma.timeProposal.findMany()
   * 
   * // Get first 10 TimeProposals
   * const timeProposals = await prisma.timeProposal.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timeProposalWithIdOnly = await prisma.timeProposal.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimeProposalFindManyArgs>(args?: Prisma.SelectSubset<T, TimeProposalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TimeProposal.
   * @param {TimeProposalCreateArgs} args - Arguments to create a TimeProposal.
   * @example
   * // Create one TimeProposal
   * const TimeProposal = await prisma.timeProposal.create({
   *   data: {
   *     // ... data to create a TimeProposal
   *   }
   * })
   * 
   */
  create<T extends TimeProposalCreateArgs>(args: Prisma.SelectSubset<T, TimeProposalCreateArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TimeProposals.
   * @param {TimeProposalCreateManyArgs} args - Arguments to create many TimeProposals.
   * @example
   * // Create many TimeProposals
   * const timeProposal = await prisma.timeProposal.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimeProposalCreateManyArgs>(args?: Prisma.SelectSubset<T, TimeProposalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TimeProposals and returns the data saved in the database.
   * @param {TimeProposalCreateManyAndReturnArgs} args - Arguments to create many TimeProposals.
   * @example
   * // Create many TimeProposals
   * const timeProposal = await prisma.timeProposal.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TimeProposals and only return the `id`
   * const timeProposalWithIdOnly = await prisma.timeProposal.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TimeProposalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TimeProposalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TimeProposal.
   * @param {TimeProposalDeleteArgs} args - Arguments to delete one TimeProposal.
   * @example
   * // Delete one TimeProposal
   * const TimeProposal = await prisma.timeProposal.delete({
   *   where: {
   *     // ... filter to delete one TimeProposal
   *   }
   * })
   * 
   */
  delete<T extends TimeProposalDeleteArgs>(args: Prisma.SelectSubset<T, TimeProposalDeleteArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TimeProposal.
   * @param {TimeProposalUpdateArgs} args - Arguments to update one TimeProposal.
   * @example
   * // Update one TimeProposal
   * const timeProposal = await prisma.timeProposal.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimeProposalUpdateArgs>(args: Prisma.SelectSubset<T, TimeProposalUpdateArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TimeProposals.
   * @param {TimeProposalDeleteManyArgs} args - Arguments to filter TimeProposals to delete.
   * @example
   * // Delete a few TimeProposals
   * const { count } = await prisma.timeProposal.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimeProposalDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimeProposalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeProposals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TimeProposals
   * const timeProposal = await prisma.timeProposal.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimeProposalUpdateManyArgs>(args: Prisma.SelectSubset<T, TimeProposalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeProposals and returns the data updated in the database.
   * @param {TimeProposalUpdateManyAndReturnArgs} args - Arguments to update many TimeProposals.
   * @example
   * // Update many TimeProposals
   * const timeProposal = await prisma.timeProposal.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TimeProposals and only return the `id`
   * const timeProposalWithIdOnly = await prisma.timeProposal.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TimeProposalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TimeProposalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TimeProposal.
   * @param {TimeProposalUpsertArgs} args - Arguments to update or create a TimeProposal.
   * @example
   * // Update or create a TimeProposal
   * const timeProposal = await prisma.timeProposal.upsert({
   *   create: {
   *     // ... data to create a TimeProposal
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TimeProposal we want to update
   *   }
   * })
   */
  upsert<T extends TimeProposalUpsertArgs>(args: Prisma.SelectSubset<T, TimeProposalUpsertArgs<ExtArgs>>): Prisma.Prisma__TimeProposalClient<runtime.Types.Result.GetResult<Prisma.$TimeProposalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TimeProposals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalCountArgs} args - Arguments to filter TimeProposals to count.
   * @example
   * // Count the number of TimeProposals
   * const count = await prisma.timeProposal.count({
   *   where: {
   *     // ... the filter for the TimeProposals we want to count
   *   }
   * })
  **/
  count<T extends TimeProposalCountArgs>(
    args?: Prisma.Subset<T, TimeProposalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeProposalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TimeProposal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeProposalAggregateArgs>(args: Prisma.Subset<T, TimeProposalAggregateArgs>): Prisma.PrismaPromise<GetTimeProposalAggregateType<T>>

  /**
   * Group by TimeProposal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeProposalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimeProposalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimeProposalGroupByArgs['orderBy'] }
      : { orderBy?: TimeProposalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimeProposalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeProposalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TimeProposal model
 */
readonly fields: TimeProposalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TimeProposal.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimeProposalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointment<T extends Prisma.AppointmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppointmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  proposedBlock<T extends Prisma.AvailabilityBlockDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AvailabilityBlockDefaultArgs<ExtArgs>>): Prisma.Prisma__AvailabilityBlockClient<runtime.Types.Result.GetResult<Prisma.$AvailabilityBlockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  status<T extends Prisma.ProposalStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProposalStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__ProposalStatusClient<runtime.Types.Result.GetResult<Prisma.$ProposalStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TimeProposal model
 */
export interface TimeProposalFieldRefs {
  readonly id: Prisma.FieldRef<"TimeProposal", 'String'>
  readonly appointmentId: Prisma.FieldRef<"TimeProposal", 'String'>
  readonly proposedBlockId: Prisma.FieldRef<"TimeProposal", 'String'>
  readonly message: Prisma.FieldRef<"TimeProposal", 'String'>
  readonly statusId: Prisma.FieldRef<"TimeProposal", 'String'>
  readonly createdAt: Prisma.FieldRef<"TimeProposal", 'DateTime'>
  readonly respondedAt: Prisma.FieldRef<"TimeProposal", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TimeProposal", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TimeProposal findUnique
 */
export type TimeProposalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter, which TimeProposal to fetch.
   */
  where: Prisma.TimeProposalWhereUniqueInput
}

/**
 * TimeProposal findUniqueOrThrow
 */
export type TimeProposalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter, which TimeProposal to fetch.
   */
  where: Prisma.TimeProposalWhereUniqueInput
}

/**
 * TimeProposal findFirst
 */
export type TimeProposalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter, which TimeProposal to fetch.
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeProposals to fetch.
   */
  orderBy?: Prisma.TimeProposalOrderByWithRelationInput | Prisma.TimeProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeProposals.
   */
  cursor?: Prisma.TimeProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeProposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeProposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeProposals.
   */
  distinct?: Prisma.TimeProposalScalarFieldEnum | Prisma.TimeProposalScalarFieldEnum[]
}

/**
 * TimeProposal findFirstOrThrow
 */
export type TimeProposalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter, which TimeProposal to fetch.
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeProposals to fetch.
   */
  orderBy?: Prisma.TimeProposalOrderByWithRelationInput | Prisma.TimeProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeProposals.
   */
  cursor?: Prisma.TimeProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeProposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeProposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeProposals.
   */
  distinct?: Prisma.TimeProposalScalarFieldEnum | Prisma.TimeProposalScalarFieldEnum[]
}

/**
 * TimeProposal findMany
 */
export type TimeProposalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter, which TimeProposals to fetch.
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeProposals to fetch.
   */
  orderBy?: Prisma.TimeProposalOrderByWithRelationInput | Prisma.TimeProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TimeProposals.
   */
  cursor?: Prisma.TimeProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeProposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeProposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeProposals.
   */
  distinct?: Prisma.TimeProposalScalarFieldEnum | Prisma.TimeProposalScalarFieldEnum[]
}

/**
 * TimeProposal create
 */
export type TimeProposalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * The data needed to create a TimeProposal.
   */
  data: Prisma.XOR<Prisma.TimeProposalCreateInput, Prisma.TimeProposalUncheckedCreateInput>
}

/**
 * TimeProposal createMany
 */
export type TimeProposalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TimeProposals.
   */
  data: Prisma.TimeProposalCreateManyInput | Prisma.TimeProposalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TimeProposal createManyAndReturn
 */
export type TimeProposalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * The data used to create many TimeProposals.
   */
  data: Prisma.TimeProposalCreateManyInput | Prisma.TimeProposalCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TimeProposal update
 */
export type TimeProposalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * The data needed to update a TimeProposal.
   */
  data: Prisma.XOR<Prisma.TimeProposalUpdateInput, Prisma.TimeProposalUncheckedUpdateInput>
  /**
   * Choose, which TimeProposal to update.
   */
  where: Prisma.TimeProposalWhereUniqueInput
}

/**
 * TimeProposal updateMany
 */
export type TimeProposalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TimeProposals.
   */
  data: Prisma.XOR<Prisma.TimeProposalUpdateManyMutationInput, Prisma.TimeProposalUncheckedUpdateManyInput>
  /**
   * Filter which TimeProposals to update
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * Limit how many TimeProposals to update.
   */
  limit?: number
}

/**
 * TimeProposal updateManyAndReturn
 */
export type TimeProposalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * The data used to update TimeProposals.
   */
  data: Prisma.XOR<Prisma.TimeProposalUpdateManyMutationInput, Prisma.TimeProposalUncheckedUpdateManyInput>
  /**
   * Filter which TimeProposals to update
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * Limit how many TimeProposals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TimeProposal upsert
 */
export type TimeProposalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * The filter to search for the TimeProposal to update in case it exists.
   */
  where: Prisma.TimeProposalWhereUniqueInput
  /**
   * In case the TimeProposal found by the `where` argument doesn't exist, create a new TimeProposal with this data.
   */
  create: Prisma.XOR<Prisma.TimeProposalCreateInput, Prisma.TimeProposalUncheckedCreateInput>
  /**
   * In case the TimeProposal was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimeProposalUpdateInput, Prisma.TimeProposalUncheckedUpdateInput>
}

/**
 * TimeProposal delete
 */
export type TimeProposalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
  /**
   * Filter which TimeProposal to delete.
   */
  where: Prisma.TimeProposalWhereUniqueInput
}

/**
 * TimeProposal deleteMany
 */
export type TimeProposalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeProposals to delete
   */
  where?: Prisma.TimeProposalWhereInput
  /**
   * Limit how many TimeProposals to delete.
   */
  limit?: number
}

/**
 * TimeProposal without action
 */
export type TimeProposalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeProposal
   */
  select?: Prisma.TimeProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeProposal
   */
  omit?: Prisma.TimeProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeProposalInclude<ExtArgs> | null
}
